# 介绍 {#author .unnumbered}

每个人都写作。尤其是在学术界。学生写作，教授写作。非小说类作家是本书旨在帮助的第三类人，他们显然也在写作。写作并不一定意味着论文、文章或书籍，而是日常的基本写作。当我们需要记住某件事的时候，我们就写作，无论是一个想法、一句话还是一项研究的结果。当我们想整理自己的想法，当我们想与他人交流想法时，我们就写作。学生们在考试时写作，但即使是准备口试，他们做的第一件事就是拿起笔和纸。我们不仅要写下那些我们害怕不记住的东西，还要写下我们试图记住的东西。每一次智力上的努力都是从一个音符开始的。

写作在学习、学习和研究中扮演着如此重要的角色，以至于我们对写作的思考如此之少，这是令人惊讶的。如果讨论写作，重点几乎总是放在我们写一篇长篇文章、一本书、一篇文章，或者作为学生，写我们必须交的论文和论文的少数特殊时刻。乍一看，这是有道理的：这些任务是最令人焦虑的，也是我们挣扎时间最长的。因此，这些“书面作品”也是大多数学者自助书籍或学习指南关注的内容，但很少有人能为占我们写作大部分的日常笔记提供指导。

现有书籍大致分为两类。第一个课程讲授形式要求：风格、结构或如何正确引用。还有心理因素，它教会你如何在你的主管或出版商再次拒绝改变截止日期之前，在没有精神崩溃的情况下完成它。然而，他们的共同点是，他们都是从一个空白的屏幕或一张纸开始的。\[1\]但是通过这样做，他们忽略了主要部分，即记笔记，没有理解改善所有写作的“组织”会带来不同。他们似乎忘记了写作的过程比空白屏幕开始得早得多，而实际写下的论点是其发展的最小部分。本书旨在通过向您展示如何有效地将您的想法和发现转化为令人信服的书面作品，并在这一过程中积累智慧和相互关联的笔记，从而填补这一空白。你可以使用这些笔记，不仅可以让自己的写作更轻松、更有趣，还可以长期学习并产生新的想法。但最重要的是，你每天都可以用一种能推进你的项目的方式来写作。

写作不是研究、学习或学习之后的事情，它是所有这些工作的媒介。也许这就是为什么我们很少思考写作，日常写作，笔记和草稿的原因。就像呼吸一样，它对我们所做的事情至关重要，但因为我们经常这样做，它就逃避了我们的注意。但是，即使是最好的呼吸技巧也不会对我们的写作产生很大的影响，但是我们每天写作的方式，我们如何记录我们遇到的事情，以及我们如何对待它们，都会在我们面对空白页/屏幕时——或者更确切地说，No.To，产生不同的效果。因为那些记笔记的人再也不会有空白屏幕的问题了。

还有另一个原因是，记笔记的人往往不被注意到：如果做得不好，我们不会立即收到任何负面反馈。但如果没有直接的失败经验，也没有太多的帮助需求。而出版市场如何运作，对于这种需求的缺乏也没有多少帮助。正是在空白屏幕前的恐慌，使学生和学术作家转向书架上充满了自助写作的书籍，市场出版商成群结队地集中讨论如何处理这匹马已经离开谷仓的情况。如果我们记笔记不系统、效率低下或根本错误，我们甚至可能意识不到这一点，直到我们陷入了最后期限恐慌之中，并想知道为什么总是有一些人写了很多好文章，但每次我们问他们时，他们仍然有时间喝咖啡。即便如此，更可能的是，某种形式的合理化会掩盖对实际原因的看法，这很可能是好笔记和坏笔记之间的区别。“有些人就是这样”，“写作一定很难”，“奋斗是交易的一部分”只是一些咒语，让太多人无法探究成功的写作策略和不成功的写作策略之间究竟有什么区别。

正确的问题是：在未来的几周、几个月甚至几年里，我们能做些什么不同的事情？我们面对一个空白页，它能让我们尽可能地写出一篇好文章。很少有人因为不知道如何正确引用或者因为他们的心理问题而无法写作而在论文中苦苦挣扎。很少有人挣扎着给朋友发短信或写电子邮件。引用规则是可以查到的，不可能有论文延期那么多的心理问题。大多数人为了更平凡的原因而奋斗，一个是空白页本身的神话。他们之所以挣扎，是因为他们相信，正如他们被迫相信的那样，写作是从空白页开始的。如果你认为你手头确实没有什么东西可以填补，你就有很好的理由感到恐慌。仅仅把这些都记在脑子里是不够的，因为把它们写在纸上是很难的。这就是为什么好的、富有成效的写作是建立在良好的笔记基础上的。把已经写在另一篇文章里的东西写出来比把所有的东西都放在脑子里然后试图从那里取回要容易得多。

总而言之：一篇论文的质量和写作的难易程度比任何事情都更取决于你在对主题做出决定之前在写作中做了什么。但如果这是真的（我完全相信是真的），并且成功写作的关键在于准备，这也意味着绝大多数自助书籍和学习指南只能帮助你根据官方规定正确地关上谷仓门——而不仅仅是一瞬间，但在这匹马已经逃走几个月之后。

考虑到这一点，不足为奇的是，学术成功最重要的指标不是在人们的头脑中，而是在他们日常工作的方式中。事实上，高智商与学业成功之间没有可测量的相关性——至少在120岁以下的人群中没有。是的，一定的智力能力有助于进入学术界，如果你在智商测试中苦苦挣扎，很可能你也会在解决学术问题上苦苦挣扎。但一旦你成功了，高智商既不能帮助你脱颖而出，也不能保护你免于失败。在整个智力谱中，能产生显著差异的是：一个人在处理手头的任务时使用了多少自律或自控能力（Duckworth和Seligman，2005年；Tangney，Baumeister和Boone，2004年）。

你是谁并不重要，重要的是你做什么。做所需的工作，并以一种明智的方式去做，不知何故，毫不奇怪地，会带来成功。乍一看，这既是好消息也是坏消息。好消息是，我们无论如何也不能在智商方面做太多的事情，而我们似乎可以通过一点意志力来加强自律。坏消息是我们没有这种控制自己的能力。单凭意志力是不容易做到自律或自控的。就我们今天所知，意志力是一种有限的资源，很快就会消耗殆尽，而且从长远来看也没有太多需要改进的地方（Baumeister、Bratslavsky、Muraven和Tice，1998年；Muraven、Tice和Baumeister，1998年；Schmeichel、Vohs和Baumeister，2003年；Moller，2006年）。不管怎样，谁会想鞭笞自己去工作呢？

幸运的是，这并不是全部。我们今天知道，自我控制和自律与我们的环境比与我们自己的关系要大得多（参见Thaler，2015，第2章）——环境是可以改变的。当周围没有巧克力时，没有人需要意志力不吃巧克力。没有人需要意志力去做他们想做的事情。每一项有趣、有意义和定义明确的任务都会完成，因为长期利益和短期利益之间没有冲突。有一个有意义和明确定义的任务每次都胜过意志力。没有意志力，但不必使用意志力表明你为成功做好了准备。这就是写作和记笔记的组织发挥作用的地方。
