\mainmatter

# 你需要知道的一切 {#intro}

到目前为止，写作和记笔记技术通常都是在不考虑总体工作流程的情况下教授的。这本书旨在改变这种状况。它将向你展示记录的工具，这些工具使一位酿酒师的儿子成为20世纪最有生产力和最受尊敬的社会科学家之一。但是，它还描述了他是如何在他的工作流程中实现这些功能的，这样他就可以诚实地说：“我从不强迫自己做任何我不想做的事情。每当我陷入困境时，我都会做其他事情。”一个好的结构可以让你做到这一点，无缝地从一项任务转移到另一项任务，而不会威胁到整个安排或忽略全局。

良好的结构是你可以信任的。它减轻了你记忆和记录一切的负担。如果你能信任这个系统，你就可以放弃把一切都集中在头脑中的想法，开始关注重要的东西：内容、论点和想法。通过将“写论文”这一无定形的任务分解为小而清晰的任务，你可以一次专注于一件事，一次完成每件事，然后继续下一件事（第3.1章）。一个好的结构可以使你完全沉浸在工作中，以至于你忘记了时间，可以在工作变得轻松时继续工作（Csikszentmihalyi，1975）。这样的事情不是偶然发生的。

作为学生、研究人员和非小说作家，我们比其他人有更多的自由来选择我们想花时间在什么上。尽管如此，我们经常与拖延和动机作斗争。这当然不是缺少有趣的话题，而是使用了有问题的工作程序，而不是让我们朝着正确的方向引导过程。一个好的、结构化的工作流让我们重新负责，并增加我们在正确的时间做正确事情的自由度。

有一个清晰的工作结构与制定计划是完全不同的。如果你制定了一个计划，你就给自己强加了一个结构；它使你变得死板。要继续按计划进行，你必须强迫自己并运用意志力。这不仅会降低积极性，而且也不适合像研究、思考或一般学习这样的开放式过程，在这种过程中，我们必须根据每一个新的见解、理解或成就来调整我们的下一步——理想情况下，这是我们定期拥有的，而不仅仅是例外。尽管计划常常与研究和学习的理念不一致，但它是大多数学习指南和学术写作自助书籍的口头禅。你如何计划洞察，根据定义，这是无法预料的？这是一个巨大的误解，即除了计划之外，唯一的选择就是漫无目的地胡闹。挑战在于如何构建一个人的工作流程，使洞察力和新想法成为推动我们前进的动力。我们不想让自己依赖于一个受到意外威胁的计划，比如新想法、新发现或新见解。

不幸的是，即使是大学也试图把学生变成规划师。当然，如果你坚持并通过考试，计划将帮助你通过考试。但这并不能让你成为学习/写作/记笔记艺术方面的专家（有关于这方面的研究：参见第1.3章）。计划者也不太可能在完成考试后继续学习。他们很高兴事情结束了。另一方面，专家们甚至不会考虑自愿放弃那些已经证明是有益的和有趣的事情：以一种产生真正洞察力的方式学习，积累起来，激发出新的想法。你投资这本书的事实告诉我，你宁愿做专家也不愿做规划师。

如果你是一个在写作方面寻求帮助的学生，那么你很可能已经有了很高的目标，因为通常是最优秀的学生最努力。好学生会绞尽脑汁思考句子，因为他们关心找到正确的表达方式。他们需要更长的时间来找到一个好的想法来写，因为他们从经验中知道，第一个想法很少是伟大的，好的问题不会落入他们的圈套。他们花更多的时间在图书馆里，以便更好地了解文献，这将导致更多的阅读，这意味着他们必须处理更多的信息。读得更多并不意味着就自然而然地有了更多的想法。特别是在一开始，这意味着要处理的想法更少，因为你知道其他人已经想到了其中的大部分。

优秀的学生也会超越表面现象。他们窥视自己学科的围墙——一旦你做到了这一点，你就不能回去做其他人正在做的事情，即使你现在必须处理各种各样的想法，而这些想法没有一本手册来说明它们如何结合在一起。所有这一切意味着需要一个系统来跟踪不断增加的信息库，它允许人们以智能的方式将不同的想法结合起来，以产生新的想法。

贫困学生没有这些问题。只要他们坚持在自己学科的范围内，只读要求读的内容（或更少），就不需要严肃的外部系统，坚持“如何写科学论文”的常规公式就可以完成写作。事实上，贫困学生通常会觉得更成功（直到他们被测试），因为他们没有太多的自我怀疑。在心理学中，这被称为邓宁-克鲁格效应（克鲁格和邓宁，1999）。贫困学生缺乏对自身局限性的洞察——因为他们必须了解大量的知识，才能看到相比之下他们知道的是多么少。这意味着那些不擅长某件事的人往往过于自信，而那些努力的人往往低估了自己的能力。贫困学生也很容易找到一个问题来写：他们既不缺乏意见，也不缺乏已经思考过的信心。他们在文献中找到确凿的证据也不会有困难，因为他们通常缺乏兴趣和技能来发现和思考不确凿的事实和论点。

另一方面，优秀的学生在专注于他们尚未学习和掌握的东西时，会不断为自己提高标准。这就是为什么体验过大量知识的高成就者可能会患上心理学家称之为“冒名顶替者综合症”（importer syndrome）的原因，这种感觉是你无法胜任工作，尽管在所有人中，他们都是（Clance and Imes 1978；Brems et al.1994）。这本书是给你们的，好学生，有抱负的学者和好奇的非小说作家，他们明白洞察力来之不易，写作不仅是为了发表观点，而且是实现见解值得分享的主要工具。

## 好的解决方案很简单

没有必要建立一个复杂的系统，也没有必要重新组织你已经拥有的一切。你可以通过智能笔记立即开始工作和发展想法。

不过，复杂性是一个问题。即使你的目标不是发展一个宏大的理论，只是想跟踪你所读的内容，整理你的笔记，发展你的思想，你也必须处理越来越复杂的内容，特别是因为它不仅仅是收集思想，而是建立联系和激发新思想。大多数人试图通过将他们拥有的东西分成更小的堆栈、堆或单独的文件夹来降低复杂性。他们按主题和子主题对笔记进行排序，这样看起来不那么复杂，但很快就会变得非常复杂。此外，它还降低了在笔记本身之间构建和发现惊人联系的可能性，这意味着在可用性和有用性之间进行权衡。

谢天谢地，我们不必在可用性和有用性之间做出选择。恰恰相反。处理复杂问题的最好方法是尽可能简单，并遵循一些基本原则。该结构的简单性允许在我们想要的地方构建复杂性：在内容级别。关于这一现象有相当广泛的实证和逻辑研究（概述：参见Sull和Eisenhardt，2015）。记智能笔记很简单。

另一个好消息是，你必须投入大量的时间和精力来开始工作。即使你会大大改变你的阅读、笔记和写作方式，也几乎不需要准备时间（除了理解原理和安装一两个免费程序）。这不是重做你以前做过的事情，而是从现在开始改变工作方式。真的没有必要重组你已经拥有的任何东西。不管怎样，在你必须处理事情的那一刻，就用不同的方式来处理它们。

还有更多的好消息。没有必要重新发明轮子。我们只需要将两个众所周知且行之有效的想法结合起来。第一个想法是在这本书的核心，是简单的滑箱技术。我将在下一章解释这个系统的原理，并展示如何在学生、学者或非小说作家的日常生活中实现它。谢天谢地，所有主要操作系统都有数字版本，但如果您愿意，也可以使用笔和纸。就工作效率和轻松程度而言，你仍将轻松超越那些记不太聪明笔记的人。

第二个想法同样重要。如果你不改变你的日常生活，即使是最好的工具也不会显著提高你的工作效率，就像如果你没有合适的道路行驶，最快的汽车也帮不了你。就像行为上的每一次改变一样，工作习惯的改变意味着你要经历一个阶段，回到你原来的生活方式。新的工作方式一开始可能会让人觉得做作，而不一定像你直觉上会做的那样。这是正常的。但一旦你习惯了做聪明的笔记，你就会觉得很自然，你会想知道你以前是怎么做到的。例程需要简单、可重复的任务，这些任务可以自动完成并无缝地结合在一起（参见Mata、Todd和Lippke，2010）。只有当所有相关的工作成为一个整体的、相互关联的过程的一部分，所有的瓶颈都消除了，才能发生重大的变化（这就是为什么你在互联网上找到的典型的“提高生产力的十大令人兴奋的工具”提示都不会有多大帮助）。

总体工作流程的重要性在于David Allen的“完成工作”（Allen，2001）的深刻见解。很少有认真的知识工作者没有听说过“GTD”，这有一个很好的理由：它是有效的。GTD的原则是在一个地方收集所有需要处理的东西，并以标准化的方式进行处理。这并不一定意味着我们实际上做了我们曾经打算做的每件事，但它迫使我们做出明确的选择，并定期检查我们的任务是否符合大局。只有当我们知道从重要到琐碎的每件事都得到了处理，我们才能放手，专注于眼前的事情。只有当我们的工作记忆中没有其他东西挥之不去，并且占据了宝贵的精神资源时，我们才能体验艾伦所说的“心如水”的状态——在这种状态下，我们可以专注于眼前的工作，而不会被相互竞争的思想分散注意力。这个原则很简单，但很全面。这不是一个快速修复或花哨的工具。它不适合你。但它确实为我们的日常工作提供了一个结构，处理这样一个事实：大多数分心不是来自我们的环境，而是来自我们自己的思想。

不幸的是，大卫·艾伦的技巧不能简单地转移到有洞察力的写作任务上。第一个原因是GTD依赖于明确定义的目标，而洞察力不能通过定义预先确定。我们通常从模糊的想法开始，这些想法必然会改变，直到在我们的研究过程中变得更加清晰（参见Ahrens，2014，134f.）。因此，以洞察为目的的写作必须以更加开放的方式组织。另一个原因是GTD要求将项目分解为更小、具体的“下一步”。当然，有见地的写作或学术工作也是一步一步完成的，但这些往往太小，不值得写下来（查阅脚注、重读章节、写段落）或者太过宏大而无法一次完成。也很难预测下一步之后必须采取哪一步。您可能会注意到一个脚注，您可以快速查看它。你试图理解一个段落，需要查找一些需要澄清的内容。你做一个笔记，继续阅读，然后跳起来写下一个在你脑海中形成的句子。

写作不是一个线性过程。我们必须经常在不同的任务之间来回跳跃。在这个层面上对自己进行微观管理是没有任何意义的。缩小到更大的画面也没有真正的帮助，因为接下来我们还有“写一页”之类的步骤。这对导航你写一页需要做的事情没有真正的帮助，通常是一大堆其他事情，可能需要一个小时或一个月的时间。一个人必须主要靠视觉导航。虽然GTD在商业上非常成功，并且在个体经营者中享有良好声誉，但这可能就是GTD从未真正在学术界流行的原因。

我们可以从艾伦那里得到一个重要的启示，那就是一个成功的组织的秘密在于整体的观点。每件事都要处理好，否则被忽视的部分会困扰我们，直到不重要的任务变得紧迫。如果孤立使用，即使是最好的工具也不会有多大区别。只有将这些工具嵌入到精心设计的工作流程中，这些工具才能发挥其优势。如果这些工具不适合使用，那么拥有它们是没有意义的。

说到写作，从研究到校对，一切都是紧密相连的。所有的小步骤都必须以一种方式连接起来，使您能够无缝地从一项任务转到另一项任务，但仍然保持足够的独立性，使我们能够灵活地完成在任何给定情况下需要完成的任务。这是David Allen的另一个见解：只有当你能够信任你的系统，只有当你真正知道一切都会得到解决，你的大脑才会放手，让你专注于手头的任务。

这就是为什么我们需要一个像GTD一样全面的笔记系统，但是一个适合写作、学习和思考的开放式过程的笔记系统。进入滑动框。

## 滑动框

那是20世纪60年代，在德国的某个地方。在一家德国行政办公室的职员中，有一位酿酒师的儿子。他的名字叫尼古拉斯·卢曼。他上过法学院，但他选择了做一名公务员，因为他不喜欢为多个客户工作的想法。他充分意识到自己也不适合从事管理工作，因为这涉及到大量的社交活动。每天9-5班后，他都会找借口回家做自己最喜欢做的事情：阅读并关注自己在哲学、组织理论和社会学方面的各种兴趣。

每当他遇到一些不寻常的事情，或者对他读到的东西有一个想法时，他都会做一个笔记。现在，许多人在晚上读书，关注自己的兴趣，有些人甚至做笔记。但对于很少有人来说，这是一条通往卢曼职业生涯这样非凡的道路。

在像大多数人那样收集了一段时间的笔记后，卢曼意识到他的笔记没有任何意义，他在文本的空白处发表了评论，或是按主题收集了手写的笔记。所以他把笔记放在它的头上。他没有在现有的分类或各自的文本中添加注释，而是将它们全部写在小张纸上，在角落里放一个数字，然后收集到一个地方：滑动框。

他很快就对这些音符进行了新的分类。他意识到，一个想法、一个音符的价值只在于它的上下文，而上下文并不一定是它的来源。因此，他开始思考一个想法如何与不同的背景相联系并做出贡献。仅仅在一个地方积累笔记只会产生大量的笔记。但是，他把笔记收集在自己的小盒子里，收集的方式远远超过了各部分的总和。他的滑盒成了他的对话伙伴、主要创意发生器和生产力引擎。它帮助他构建和发展他的思想。和他一起工作很有趣——因为它起作用了。

这使他进入了学术界。有一天，他把这些想法整理成一份手稿，交给德国最有影响力的社会学家之一赫尔穆特·舍尔斯基（Helmut Schelsky）。舍尔斯基把它带回家，读了这位学术界的局外人写的东西，并联系了卢曼。他建议他成为新成立的比勒费尔德大学的社会学教授。尽管这个职位很有吸引力，很有声望，但鲁曼不是社会学家。他甚至不具备成为德国社会学教授助理所需的正式资格。他没有写过一本适应训练，这是许多欧洲国家的最高学历，它是根据博士论文之后的第二本书编写的。他从未获得过博士学位，甚至没有获得过社会学学位。大多数人会把这个提议看作是一种巨大的恭维，但指出它是不可能的，然后继续前进。

不是卢曼。在不到一年的时间里，他在参加社会学课程的同时，转向了他的滑箱，在滑箱的帮助下，他完成了一篇博士论文和一篇康复论文。不久之后，在1968，他被选为比勒费尔德大学社会学教授，这将是他余生的一个职位。

在德国，教授通常以公开演讲开始，介绍他或她的项目，卢曼也被问及他的主要研究项目是什么。他的答案会出名的。他简洁地说：“我的项目：社会理论。持续时间：30年。成本：零”（卢曼，1997，11）。在社会学中，“社会理论”是所有项目之母。

几乎整整29年半后，当他完成了最后一章时，作为一本两卷的书，题为《社会的社会》（1997），它激起了科学界的骚动。\[3\]这是一种激进的新理论，不仅改变了社会学，而且在哲学、教育和科学领域引发了热烈的讨论，政治理论和心理学。不过，并不是每个人都能跟上讨论。他所做的是不同寻常的复杂，非常不同和高度复杂。各章分别出版，每本书讨论一种社会制度。他写过法律、政治、经济、传播、艺术、教育、认识论，甚至爱情。

30年来，他出版了58本书和数百篇文章，不包括翻译。许多人成为各自领域的经典。即使在他死后，仍有大约六本关于宗教、教育或政治等不同主题的书以他的名义出版——这些书都是基于他办公室里几乎完成的手稿。我认识的不止几位同事，他们愿意付出很多，在他们的一生中像卢曼死后那样富有成效。

当一些职业导向的学者试图从一个想法中挤出尽可能多的出版物时，卢曼似乎做了相反的事情。他不断地提出比他能写下的更多的想法。他的文章读起来似乎是在试图将尽可能多的见解和想法挤进一本出版物。

当有人问他一生中是否错过了什么时，他有一句名言：“如果我想要什么，那就是更多的时间。唯一真正令人讨厌的是缺少时间。”（卢曼、贝克尔和斯坦尼泽克，1987年，139）虽然一些学者让他们的助手来做主要工作，或者有一个团队来写论文，并在论文中加上他们的名字，但鲁曼几乎没有得到任何帮助。最后一位为他工作的助手发誓说，他能给予的唯一帮助就是在他的手稿中到处发现一些打字错误。Luhmann唯一真正的帮助是一名管家，他在一周内为他和他的孩子们做饭，考虑到他妻子早逝后他不得不独自抚养三个孩子，这并不特别。当然，每周五顿热饭并不能解释大约60本有影响力的书和无数文章的产生。

德国社会学家Johannes F.K.Schmidt在对Luhmann的工作流程进行了广泛研究后得出结论，他的工作效率只能用他独特的工作技术来解释（Schmidt 2013，168）。这项技术从来都不是秘密——卢曼对此一直持开放态度。他经常提到滑箱是他工作效率高的原因。早在1985年，他对一个人如何才能如此高效的问题的标准答案是：“当然，我并不是一个人思考所有事情，它主要发生在保险箱里”（卢曼、贝克尔和斯坦尼泽克，1987年，142）。但是很少有人仔细观察这个滑动框和他使用它的方式，认为他的解释是天才的谦逊的轻描淡写。

当然，他的工作效率令人印象深刻。但是，比出版数量之多或写作质量之高更令人印象深刻的是，他似乎没有付出任何努力就完成了这一切。他不仅强调他从不强迫自己去做他不想做的事情，他甚至说：“我只做容易的事情。我只在我马上知道怎么做的时候才写作。如果我一时犹豫，我会把事情放在一边，做其他事情。”（Luhmann et al.，1987，154f.\[4\]

直到最近，几乎没有人真正相信这一点。我们仍然习惯于一个伟大的结果需要付出巨大的努力，以至于我们不相信简单地改变我们的工作程序不仅能让我们更有效率，还能让工作更有趣。但是，这部令人印象深刻的作品不是尽管他从未让自己做过他不想做的事情，而是因为它而产生的，这难道不是更有意义吗？
即使是艰苦的工作也可以是有趣的，只要它与我们的内在目标相一致，并且我们感觉自己在掌控之中。当我们以一种僵化的方式来安排工作时，问题就出现了，当事情发生变化时，我们无法调整工作，并在一个似乎发展出自己生活的过程中受阻。

保持控制感的最好方法是保持控制。为了保持控制，最好在写作过程中保持开放的选择，而不是局限于你的第一个想法。写作的本质，特别是以洞察力为导向的写作，会改变问题，我们使用的材料与想象的材料有很大的不同，或者会出现新的想法，这可能会改变我们对所做事情的整体看法。只有以一种足够灵活的方式来安排工作，允许这些小而持续的调整，我们才能保持我们的兴趣、动机和工作的一致性——这是轻松或几乎轻松工作的前提。

Luhmann能够专注于他面前的重要事情，迅速从他停止的地方开始，并控制整个过程，因为他的工作结构允许他这样做。如果我们的工作环境足够灵活，能够适应我们的工作节奏，我们就不需要与阻力作斗争。对高度成功人士的研究一再证明，成功不是坚强的意志力和克服阻力的能力的结果，而是一开始避免阻力的智能工作环境的结果（参见Neal等人2012；Painter等人2002；Hearn等人1998）。和柔道冠军一样，高生产力的人不会与不利的动力抗争，而是会转移阻力。这不仅仅是要有正确的心态，也是要有正确的工作流程。正是Luhmann和他的滑箱一起工作的方式，使他能够在不同的任务和思维水平之间自由灵活地移动。这是关于拥有正确的工具并知道如何使用它们——很少有人知道你需要两者。

人们仍然在寻找卢曼的“秘密”，把他出色的表现归功于他是一个天才，甚至认为他们只需要他的滑箱就可以了。当然，要想在学术和写作上取得成功，你需要聪明，但如果你没有一个“外部”系统来思考和组织你的思想、想法和收集的事实，或者不知道如何将其融入你的日常生活，那么缺点是如此巨大，高智商无法弥补。

就技术而言，没有秘密。现在，这一切已经公开了30多年。那么，为什么不是每个人都使用滑箱，毫不费力地走向成功呢？是不是因为太复杂了？当然不是。这相当简单，令人惊讶。原因更为平凡：

1.  直到最近，当文件系统研究的第一个结果发表时，对Luhmann的实际工作方式还存在一些严重的误解，这导致许多试图模仿该系统的人的结果令人失望。主要的误解源于对滑箱的孤立关注和对其嵌入的实际工作流程的忽视。
2.  几乎所有关于这个体系的出版物都只能用德语阅读，而且几乎只在一小群专注于卢曼社会体系理论的社会学家中进行了讨论——这几乎不是一种会引起广泛关注的临界质量。
3.  第三个，也许是最重要的原因，就是它很简单。直觉上，大多数人对简单的想法期望不大。他们认为，令人印象深刻的结果必须有同样令人印象深刻的复杂手段。

亨利·福特的同时代人不明白为什么像传送带这样简单的东西应该是革命性的。让汽车在工人之间移动，而不是让工人从一辆车走到另一辆车，这有什么区别？如果他们中的一些人甚至认为福特有点头脑简单，对工作组织中一个相当小的变化过于热情，我也不会感到惊讶。这只是事后诸葛亮，规模的优势，这一小调整变得显而易见的每个人。我想知道需要多长时间，卢曼的滑箱和工作程序的优势才能对每个人都同样明显。但到那时，所有人都已经知道了这一点。

不管原因是什么：这个词现在已经说出来了，如果它传播得很快，我也不会感到惊讶。

## 滑箱手册

这个系统的核心——滑箱是如何工作的？

严格地说，卢曼有两个滑箱：一个是书目滑箱，其中包含文献内容的参考资料和简要说明；另一个是主要滑箱，其中他收集并产生了自己的想法，主要是为了回应他所阅读的内容。笔记写在索引卡上，储存在木箱中。

每当他读到什么东西时，他都会把书目信息写在卡片的一边，并在另一边对内容做简短的笔记（Schmidt 2013，170）。这些笔记最后会放在参考书目滑动框中。

在第二步中，不久之后，他会看他的简短笔记，思考它们与他自己的思考和写作的相关性。然后，他会转向主滑动框，将自己的想法、评论和想法写在新的纸上，每个想法只使用一张纸，并将自己限制在纸的一侧，以便以后阅读时更容易，而无需将其从框中取出。他通常会让它们足够简短，使一个想法可以放在一张纸上，但有时会添加另一个注释来扩展一个想法。

他写笔记时通常着眼于滑箱中已有的笔记。虽然有关文献的笔记很简短，但他写得非常仔细，与最终手稿中的风格没有太大区别：用完整的句子，并明确提及他从中提取材料的文献。通常情况下，一个新的音符会直接跟随另一个音符，并成为更长的音符链的一部分。然后，他会在滑动框中的其他地方添加注释，其中一些注释位于附近，另一些注释位于完全不同的区域和上下文中。有些是直接相关的，读起来更像是评论，另一些则没有那么明显的联系。一张纸条很少会被孤立。

他不只是从他所读的文本中抄袭想法或引用，而是从一种语境过渡到另一种语境。这很像一个翻译，你使用不同的词来适应不同的语境，但努力保持原意尽可能真实。写一篇作者在一章中努力证明其方法的文章，可以比引述文本本身更充分地描述本章的内容（当然，这需要解释）。

诀窍在于，他没有按主题组织笔记，而是以一种相当抽象的方式给它们固定的数字。这些数字没有任何意义，只是用来永久地识别每个音符。如果一个新的注释与已存在的注释相关或直接引用，例如注释、更正或添加，则他将其直接添加到前一注释后面。如果现有票据编号为22，新票据将成为票据编号23。如果23已经存在，他将新票据命名为22a。通过交替使用数字和字母，中间加上一些斜线和逗号，他可以随心所欲地将思绪扩展到任意多个字符串中。例如，一个关于因果关系和系统理论的注释在编号为21/3d7a6的注释之后加上了编号为21/3d7a7的注释。

每当他添加注释时，他都会检查自己的滑框中是否有其他相关注释，以便在它们之间建立可能的连接。在另一个注释后面直接添加注释只是一种方法。另一种方法是在该注释和/或其他注释上添加链接，该链接可能位于系统中的任何位置。当然，这与我们在互联网上使用超链接的方式非常相似。但是，正如我将在后面解释的那样，它们是完全不同的，如果将他的邮箱想象成个人维基百科或纸质数据库，那将是相当误导的。很明显，相似之处是存在的，但细微的差异正是这一体系的独特之处。 

通过在注释之间添加这些链接，Luhmann能够将相同的注释添加到不同的上下文中。当其他系统以预先设定的主题顺序开始时，Luhmann自下而上开发了主题，然后在他的滑动框中添加了另一个注释，他将通过排序相关其他注释的链接来排序主题。

 他的文件系统中的最后一个元素是索引，他会从索引中引用一两个注释，作为进入思路或主题的入口点。当然，带有分类链接集合的注释是很好的入口点。
 
 就这样。事实上，它甚至比这更简单，因为我们现在有了软件，使它更容易（参见第1.3章）：我们不需要像Luhmann那样手动在笔记上添加数字或剪纸。\[5\]
  
既然您已经了解了滑动框的工作原理，您只需要了解如何使用它。理解这一点的最好方法是稍微了解一下我们思考、学习和发展想法的方式。如果我被迫将其归结为一个要点，那就是：我们需要一个可靠而简单的外部结构来思考，以弥补我们大脑的局限性。但是，首先，让我来指导你用滑箱写一篇论文的过程。
