# 你需要做的一切 {#wind}

想象一下你没有从一张干净的床单开始。想象一下，某个友好的精灵（或者高薪的私人助理——不管你有什么可能得到的）为你准备了一份论文草稿。这已经是一个充分发展的论点，包括所有的参考文献、引文和一些非常聪明的想法。剩下唯一要做的就是修改这份草稿并寄出。别搞错了：还有很多工作要做，不仅仅是找到一些打字错误。编辑是需要专注的工作。你必须重新措辞一些句子，删除一到两个多余的部分，也许还要添加几个句子甚至段落来填补论点中留下的一些漏洞。但与此同时，这是一项明确的任务：没有什么是几天内无法完成的，当然也没有什么是你激励自己做的困难：当终点线在可及范围内时，每个人都会受到激励。到目前为止没有问题。

想象一下，现在你不是一个必须编辑草稿并将其转化为最终论文的人，而是一个必须准备它的人。什么有助于快速实现这一目标？如果你已经准备好了所有你需要的东西：想法、论据、引文、冗长的段落、完整的参考书目和参考资料，那肯定会让事情变得容易得多。而且不仅是现成的，而且已经按顺序排列好了，按章节的标题进行分类。这也是一个明确的任务。不用担心完美的句子（其他人会处理的），不用担心发现东西和提出想法（其他人已经处理了），你只需要专注于把一系列想法变成一个连续的文本。同样，这仍然是一项严肃的工作，如果你想让它变得伟大，你必须付出一些努力。你可能会发现一个论点中缺少一个步骤，并且必须填写它，或者你可能想重新安排一些笔记，或者遗漏一些你认为不太相关的东西。但是，同样，这不是一个压倒性的任务，幸运的是，它不需要是完美的。到目前为止没有问题。

同样可管理的任务是将已经存在的笔记整理好，特别是如果其中一半已经整理好了。信不信由你，在一个有着一连串讨论、大量材料和想法的文件系统中搜索是很有趣的。它不需要你集中注意力去表达一个句子或理解一个困难的文本。你的注意力相当放松，甚至有助于保持一种嬉戏的心态。只有聚焦范围较小，您才能看到连接和模式。你可以清楚地看到，已经建立起了一长串的讨论——这是一个很好的起点。如果您确实要查找特定的注释，则可以使用索引。到目前为止没有问题。

在这一点上，你不需要等待精灵出现，因为每一步显然不仅在你的能力范围内，而且是简单明确的：整理笔记并把它们整理好，把这些笔记变成草稿，检查一下，你就完成了。

现在，你可能会说，这一切都很好，但是写这些笔记怎么样？显然，如果文章的主要部分已经完成，只需要将其转换为线性文本，那么写一篇论文就很容易了。但这不是有点像在说：如果你缺钱，就从你的存钱罐里拿出你需要的东西吧？每个人都可以通过省略主要部分使事情看起来简单。那么，那个妖怪在哪里呢？

诚然，写这些笔记是主要工作。这将需要大量的努力、时间、耐心和毅力，你可能会在这项任务的重压下崩溃。只是开玩笑。这是最简单的部分。写这些笔记也不是主要工作。思考是重要的。阅读是最重要的。理解和提出想法是非常重要的。应该是这样的。这些笔记只是它的有形成果。你所要做的就是在做你正在做的事情时手里拿着一支笔（或者在你的手指下拿着一个键盘）。写笔记伴随着主要的工作，如果做得好，它会有帮助。毫无疑问，写作是思考、阅读、学习、理解和产生想法的最佳促进者。笔记是在你思考、阅读、理解和产生想法的同时建立起来的，因为如果你想正确地思考、阅读、理解和产生想法，你必须手里拿着一支笔。如果你想从长远角度学习一些东西，你必须把它写下来。如果你想真正理解某事，你必须把它翻译成你自己的话。思考在纸上发生的次数和在自己头脑中发生的次数一样多。神经学家尼尔·利维在《牛津大学神经伦理学手册》导言中总结了几十年的研究成果，他总结道：“纸上或电脑屏幕上的笔记[…]并不能使当代物理学或其他类型的智力研究变得更容易，它们使之成为可能。”。神经科学家、心理学家和其他思维专家对我们的大脑如何工作有着截然不同的看法，但正如莱维所写：“无论内部过程是如何实施的，（你）都需要了解大脑在多大程度上依赖于外部支架。”（2011，270）如果专家们同意一件事，然后就是这样：你必须把你的想法具体化，你必须写作。理查德·费曼和本杰明·富兰克林一样强调这一点。如果我们写作，我们更有可能理解我们读到的东西，记住我们学到的东西，并且我们的思想更有意义。如果我们不得不写作，为什么不利用我们的写作为我们未来的出版物积累资源呢？

思考、阅读、学习、理解和产生想法是每个学习、做研究或写作的人的主要工作。如果你写文章来改进所有这些活动，你就会有一股强大的顺风。如果你用聪明的方式记笔记，它会推动你前进。

## 一步一步地写论文

### 作短暂的笔记。

手头总有一些东西可以用来写，以捕捉突然出现在你脑海中的每一个想法。不要太担心你怎么写或者写在什么上面。这些都是转瞬即逝的音符，只是提醒你脑子里在想什么。它们不应该引起任何分心。把它们放在一个地方，你把它定义为你的收件箱，以后再处理它们。我通常随身带着一个简单的笔记本，但如果手边没有其他东西的话，我很乐意带上餐巾纸或收据。有时我会在手机上留下语音记录。如果你的想法已经整理好了，而且你有时间，你可以跳过这一步，直接把你的想法写下来，作为一个合适的、永久的便条，放在你的邮箱里。

### 做文学笔记。

每当你读到东西时，记下内容。写下你不想忘记的东西，或者你认为在自己的思考或写作中可能用到的东西。尽量简短，要有选择性，用你自己的话。在引用时要格外小心——不要复制它们来跳过真正理解它们含义的步骤。把这些笔记和书目细节放在一个地方——你的参考系统。

### 做永久性的笔记。

现在转到你的滑箱。仔细阅读你在第一步或第二步中所做的笔记（最好是每天一次，在你忘记你的意思之前），并思考它们与你自己的研究、思考或兴趣有何关联。这很快就可以通过查看滑动框来完成——它只包含你感兴趣的内容。这个想法不是收集，而是发展想法、论点和讨论。新的信息是否与你已有的信息相矛盾、正确、支持或补充（在滑箱中或你的脑海中）？你能把想法结合起来产生新的东西吗？他们引发了什么问题？

为每个想法只写一个注释，并像为其他人写一样写：使用完整的句子，披露你的来源，做参考，并尽可能精确、清晰和简短。扔掉第一步中稍纵即逝的笔记，把第二步中的文献笔记放到你的参考系统中。你现在可以忘记他们了。重要的是把它放进保险箱。

### 现在，通过以下方式将新的永久票据添加到滑动框中：

a) 在一个或多个相关注释后面归档每个注释（通过一个程序，您可以将一个注释“放在”多个注释后面；如果您像Luhmann一样使用笔和纸，您必须确定它最适合的位置，并添加到其他注释的手动链接）。看看新的音符与哪个音符直接相关，或者，如果它还没有与任何其他音符直接相关，就把它放在最后一个音符后面。
b) 添加相关注释的链接。
c) 通过从索引链接到该笔记，或在笔记上链接到该笔记，确保您以后能够找到该笔记，该笔记用作讨论或主题的入口点，并且本身链接到该索引。

### 从系统内部自下而上开发您的主题、问题和研究项目。

看看有什么，缺少什么，出现了什么问题。阅读更多内容来挑战和强化你的论点，并根据你正在学习的新信息来改变和发展你的论点。做更多的笔记，进一步发展想法，看看事情会把你带到哪里。只需跟随你的兴趣，始终走最有洞察力的道路。以你所拥有的为基础。即使你的邮箱里还没有任何东西，你也永远不会从零开始——你脑子里已经有了要测试的想法，要挑战的意见和要回答的问题。不要为某个话题进行头脑风暴_相反，请查看滑动框，看看注释链在哪里形成，想法在哪里形成了集群。如果另一个更有希望的想法获得动力，不要固守不放。你对某件事越感兴趣，你会读得越多，想得越多，你收集的笔记越多，你就越有可能从中产生问题。它可能正是你从一开始就感兴趣的东西，但更有可能的是你的兴趣已经改变了，这就是insight所做的。

### 过了一段时间，你就会有足够的想法来决定一个写作主题。

你现在的主题是基于你所拥有的，而不是基于你即将阅读的文献可能提供的毫无根据的想法。查看连接并收集有关此主题的所有相关注释（大多数相关注释已按部分顺序排列），将它们复制到“桌面”\[6\]，并将它们按顺序排列。寻找缺失的和多余的。不要等到你把一切都准备好了。相反，尝试想法，给自己足够的时间重新阅读和记笔记，以改进你的想法、论点和它们的结构。

### 把你的笔记变成草稿。

不要简单地把笔记抄成手稿_把它们翻译成连贯的东西，并将它们嵌入到你的论点的上下文中，同时用笔记构建你的论点。找出你论点中的漏洞，填补它们或改变你的论点。

### 编辑和校对你的手稿。

拍拍自己的肩膀，然后翻看下一篇手稿。

这些步骤就像一次只写一篇论文/文章一样。事实上，你永远不会只研究一个想法，而是同时研究不同阶段的许多想法。这就是该系统发挥其真正优势的地方。我们忍不住一次思考不止一个问题，很可能你将来也会思考和写作。这可能不是为了学术或出版，但肯定是为了你自己的智力成长。收集你在路上遇到的东西，不要浪费任何好主意。你可能会读一本书，希望它能对你写的论文有用。也许你错了，但它仍然可能包含一些有趣的想法，值得保留，并对你还没有想到的其他事情有用。

事实上，你阅读的每一篇文章都不太可能完全包含你所寻找的信息，而不包含其他信息。否则，你肯定已经知道里面有什么，一开始就没有理由去读它。\[7\]因为要想知道某件东西是否值得一读，唯一的办法就是去读它（即使只是其中的一小部分），以最好的方式利用所花的时间是有意义的。我们在阅读过程中不断遇到有趣的想法，其中只有一小部分对我们开始阅读的特定论文有用。为什么让它们浪费掉？做一个记录，并把它添加到你的滑动框中。它改进了它。每一个想法都可以成为一个临界质量，将一个想法集合变成一个想法发生器。

一个典型的工作日将包含许多（如果不是全部的话）这些步骤：阅读和做笔记。你在滑箱中建立联系，这本身就会激发新的想法。你把它们写下来并加入讨论。你写在论文上，注意到论点中的一个漏洞，然后在文件系统中再次查找丢失的链接。你继续做一个脚注，回到研究中，可能会在你正在撰写的一篇论文中添加一段合适的引语。

你想阅读的重点取决于你的优先顺序。你不必阅读任何你认为不需要完成最紧急的论文的东西，但是你仍然会遇到很多其他的想法和信息。花一点额外的时间将它们添加到你的系统中会有很大的不同，因为偶遇构成了我们学习的大部分内容。

想象一下，如果我们一生只学习我们计划学习的东西，或者被明确地教导。我怀疑我们会不会学会说话。每增加一点信息，仅通过我们的兴趣过滤，都有助于我们未来的理解、思考和写作。最好的想法通常是我们没有预料到的。

大多数人同时遵循不同的思路。他们可能会把注意力集中在一个想法上一段时间，然后再把它放在另一段时间，直到他们看到如何进一步。现在能够接受另一个想法，以后再回到先前的想法是很有帮助的。保持这种灵活性要现实得多，你不必担心从头开始。
