# 你需要的一切 {#一切}

有这样一个故事，美国宇航局试图找出如何使圆珠笔在太空中工作。如果你曾经试图用圆珠笔在头上写字，你可能已经意识到是重力让墨水流动。经过一系列原型、多次测试和投入大量资金后，美国宇航局开发了一种功能齐全的重力独立钢笔，它通过压缩氮气将墨水推到纸上。根据这个故事，俄罗斯人面临着同样的问题。所以他们使用铅笔（DeBono，1998，141）。滑箱遵循俄罗斯模式：关注要点，不要让事情变得不必要的复杂。

学术写作本身并不是一个复杂的过程，它需要各种复杂的工具，但经常有被不必要的干扰所阻塞的危险。不幸的是，随着时间的推移，大多数学生收集并接受各种各样的学习和记笔记技巧，每种技巧都有可能使事情变得更简单，但结合起来却会产生相反的效果。

整个工作流程变得复杂起来：有一种技术可以在重要的句子下划线（有时用不同的颜色或形状），在文本的空白处发表评论，撰写摘录，使用类似SQ3R\[8\]或SQ4R这样的首字母缩写的阅读方法，\[9\]写日记，集思广益讨论一个主题或遵循多步骤问题单——当然，还有一千零十二个应用程序和程序，它们应该有助于学习和写作。其中很少有技术本身特别复杂，但它们通常在使用时不考虑实际工作流程，很快就会变得一团糟。由于没有任何东西真正适合在一起，在这种安排下工作确实变得极其复杂，很难完成任何事情。

如果你偶然发现一个想法，并认为它可能与另一个想法相联系，那么当你使用所有这些不同的技术时，你会怎么做？通读你所有的书，找出正确的带下划线的句子？重读你所有的日记和摘录？那你怎么办？写一篇关于它的摘录？您将其保存在何处？这对建立新连接有何帮助？每一小步都会突然变成自己的计划，而不会使整个计划向前推进很多。那么，给它添加另一种有前途的技术只会让事情变得更糟。

这就是为什么滑箱不是作为另一种技术引入的原因，而是作为一个总体工作流程中的一个关键元素引入的，这个总体工作流程去除了所有可能分散重要内容注意力的内容。好的工具不会在我们已有的基础上增加功能和更多选项，但有助于减少对主要工作的干扰，这就是“思考”。滑动框提供了一个外部支架，可以进行思考，并帮助我们完成大脑不擅长的任务，尤其是客观存储信息。

差不多就是这样。我们所需要的就是拥有一个不受干扰的大脑和一个可靠的笔记集。其他一切都是乱七八糟的。

## 工具箱

我们需要四个工具：

· 写字用的东西和写字用的东西（笔和纸就可以了）
· 参考管理系统（最好的程序是免费的）
· 滑箱（最好的程序是免费的）
· 编辑（任何对你最合适的：非常好的都是免费的）


多是不必要的，少是不可能的。

1.无论何时何地，你都需要一些东西来捕捉想法。无论你使用什么，都不需要任何想法、注意力或多个步骤来写下来。它可以是笔记本、餐巾、手机或iPad上的应用程序。这些笔记不应永久保存。无论如何，它们很快就会被删除或丢弃。它们只起到提醒思想的作用，并不意味着捕捉思想本身，这需要时间来表达正确的句子和检查事实。我建议你随身携带纸笔。在简单性方面，真的很难打败笔记本电脑。如果你使用其他工具，确保所有东西都放在一个地方，一个中央收件箱或类似的地方，在那里你可以很快处理，最好是在一天之内。

2.参考资料系统有两个目的：收集参考资料（duh）和阅读过程中的笔记。我强烈建议您使用Zotero这样的免费程序，它允许您通过浏览器插件或仅通过输入ISBN或数字对象标识符（DOI）号码来创建新条目。Zotero还可以集成到MicrosoftWord、OpenOffice、LibreOffice和NeoOffice中，这样您就可以插入引用，而无需实际键入引用。这不仅使事情变得更容易，还可以降低在添加、编辑或删除其他引用时出错的风险。你也可以根据你的教授或你为之撰写的期刊所要求的标准轻松地更改格式。您可以在每个条目中添加注释，但如果您在这个阶段更喜欢手写，也可以手工编写注释并将其链接到参考文献。在这种情况下，只需给笔记一个标准化的标题，如“AuthorYear”，并将它们按字母顺序放在一个地方。你可以在Zotero.org（Windows、Mac和Linux）上免费下载Zotero。您可以在takesmartnotes.com上找到所有推荐程序的链接。[10]如果您更喜欢或已经在使用另一个同样简单的程序，没有理由不使用该程序。

3.滑箱。有些人更喜欢放在木箱里的老式纸笔版本。这很好——不管怎样，计算机只能加速相对较小的一部分工作，比如添加链接和格式化引用。他们不能加快工作的主要部分，即思考、阅读和理解。你所需要的只是一张明信片大小的纸（Luhmann使用的是DIN A6尺寸，148 x 105毫米或5.83 x 4.13英寸）和一个盒子来保存它们。即使手写有明显的好处（参见下面第3.2.1章），我还是建议使用数字版本，如果只是为了方便移动。即使你基本上可以用任何允许设置链接和标签的程序（比如Evernote或Wiki）来模拟滑动框，我还是强烈建议你使用==Daniel Lüdecke的Zettelkasten==。这是我所知道的唯一一个真正实现Luhmann系统背后原理的程序，同时简单易用。它是免费的，可用于不同的操作系统。你可以从ZETelkaseT.DayielueDeCKE.DE下载它（如果你喜欢的话，请考虑向开发者发送捐赠）。

4.最后，编辑器：如果您使用Zotero，我建议您使用与之兼容的编辑器之一（Microsoft Word、OpenOffice、LibreOffice或NeoOffice），因为如果您不必手动键入每个引用，这将使您的生活更加轻松。除此之外，一切都很好——没有一个编辑可以改进一个论点。

如果你手头有笔和纸，一个编辑器，你的滑动框和参考系统，你就可以开始了。
