# 写作是唯一重要的事情 {#唯一}

对于学生来说，写作的需要主要表现在考试的形式上。在这种理解中，书面作品代表了一种事先的表现，即学习、理解和批判性分析其他文本的能力。通过写作，学生展示他们所学到的东西，展示他们批判性思考的能力和发展想法的能力。这种理解与学生为独立研究做准备的想法有关。在这种心态下，写论文只是另一种需要学习的技能。它与其他任务分开，被视为一项任务。学生不仅要学习写论文，还要学习事实，能够在研讨会上讨论自己的想法，认真听讲。写论文本身被视为一项有起点和终点的任务。几乎所有关于学术写作的书都是从这个假设开始的。几乎所有的过程都是这样进行的，在某些连续的步骤中描述了一个理想化的过程。

首先，给出了写作任务，然后是找到一个主题或一个问题的特定角度的挑战，要做的研究，从收集相关文献开始，然后阅读材料，对其进行处理并得出结论。写作是这样的：首先是要回答的问题，然后是文献综述、讨论和结论。根据这种想法，这为你进行独立研究做好了准备。唉，事实并非如此。如果你在研究中取得了成功，那不是因为你学会了用这种方式写作，而是尽管如此。

这本书基于另一个假设：学习不会让学生为独立研究做好准备。这是一项独立的研究。没有人从零开始，每个人都已经能够独立思考了。研究，如果做得好，就是研究，因为它是为了获得无法预料的洞察力，并在公众监督下在科学界共享。学术界没有所谓的私人知识。保守秘密的想法和你从未有过的想法一样好。没有人能重现的事实根本就不是事实。公开总是意味着把它写下来以便阅读。没有不成文思想的历史。

学校是不同的。学生通常不被鼓励遵循自己的学习路径，质疑和讨论老师所教的每一件事，如果某件事不能保证产生有趣的见解，就转到另一个话题。老师在那儿让学生们学习。但是，正如柏林洪堡特大学的创始人威廉·冯·洪堡和伟大探险家亚历山大·冯·洪堡的哥哥所说的，教授不在那里，学生和学生不在教授身边。两者都只是为了真相。真相永远是一个公共事务。大学里的一切都是为了某种形式的出版。一篇书面文章不一定要在国际期刊上被接受才能公之于众。事实上，所写和讨论的绝大多数内容并不是在这种狭义上发表的。复习过程本身就是一种向同龄人公开展示想法的形式，学生交给教授或讲师的一切也是如此。甚至与同学讨论的演讲讲义也是公开的书面材料。这是公开的，因为在讨论中，作者的意思不再重要了，只有书面的内容。当作者被从现场移开的那一刻，这篇文章就是对真相的公开宣称。无论作者是谁或出版商的身份如何，令人信服的论据的标准始终是相同的：它们必须连贯一致并以事实为基础。真理不属于任何人；它是书面思想科学交流的结果。这就是为什么知识的呈现和产生不能分开，而是同一枚硬币的两面（Peters和Schäfer 2006，9）。如果写作是研究的媒介，研究只是研究，那么就没有理由不工作，就好像没有什么比写作更重要一样。

像写作一样工作并不意味着花更多的时间写作而牺牲了其他一切。只有当我们把工作划分成不同的、孤立的任务时，专注于写作似乎会减少我们花在其他任务上的时间。但这并不意味着要少读，因为这是写作材料的主要来源。这并不意味着少参加讲座或研讨会，因为它们为你们提供了写作的想法和值得回答的问题。参加讲座也是了解当前研究状况的最佳方式之一，更不用说提问和讨论问题的能力了。专注于写作并不意味着停止做演讲或寻找其他方式来公开你的想法。你还可以从哪里获得你的想法的反馈？

把注意力集中在写作上，好像其他事情都不重要，并不一定意味着你应该把其他事情做得不那么好，但这肯定会让你把其他事情做得不一样。当你参加讲座、讨论会或研讨会时，有一个明确、明确的目标会让你更加投入，并使你的注意力更加集中。你不会把时间浪费在试图弄清楚你“应该”学什么上。相反，你将尽可能高效地学习，这样你就可以迅速找到真正的开放性问题，因为这些是唯一值得写的问题。你很快就会学会区分听起来不错的论点和实际的好论点，因为每当你试图把它们写下来，并将它们与你以前的知识联系起来时，你都必须仔细思考。它也会改变你的阅读方式：你会更加专注于最相关的方面，知道你不能把一切都写下来。你将以一种更专注的方式阅读，因为如果你不明白它是关于什么的，你就不能用自己的话重新表述任何东西。通过这样做，你将详细阐述其含义，这将使你更有可能记住它。你还必须超越你所读的东西，因为你需要把它变成新的东西。如果你做每件事都有明确的写作目的，你就会做你有意做的事。深思熟虑的练习是让我们做得更好的唯一认真的方法（参见Anders Ericsson，2008）。如果你改变了对写作重要性的看法，你也会改变对其他一切的看法。即使你决定不写一行稿子，你也会通过做每件事来提高你的阅读、思考和其他智力技能，就好像除了写作什么都不重要一样。
