# 没有人会从零开始 {#wind-7}

“白纸——或今天：空白屏幕——是一个根本性的误解。”
(Nassehi 2015, 185)

写作的过程被极大地误解了。如果你从书架上随机拿出一本关于写作的学习指南或自助书，浏览第一页，你很可能会遇到这样的情况：“为了使你的研究更有效率，你的第一步应该是缩小你选择关注的方面，并制定一个明确的问题，你的研究和分析将解决这个问题。”\[14\]几乎所有情况下，关于该主题的决定都是作为必要的第一步提出的，然后是其他一切，如本指南中所述：“当您选择了适合自己的主题，并考虑到您的个人兴趣和可能需要的任何必要背景知识时，请评估来源的可用性。”\[15\]此后，你当然会发现你应该遵循的多步骤计划：根据澳大利亚国立大学学术技能和学习中心的十二步，或者八，如果你按照威斯康星大学写作中心的建议，粗糙的顺序总是相同的：做一个十进制。关于写什么，计划你的研究，做你的研究，写。有趣的是，这些路线图通常都有一个让步，那就是这只是一个理想化的计划，而事实上，它很少像那样起作用。这当然是真的。写作不可能是线性的。显而易见的问题是：如果这是真的，为什么不呢他在现实中采取了什么行动？

为了提出一个好的问题来写，或者为作业找到一个最佳的角度，一个人必须已经对一个主题进行了思考。为了能够决定一个主题，一个人必须已经读了很多书，当然不仅仅是一个主题。阅读某些东西而不是其他东西的决定显然植根于先前的理解，这也不是凭空而来的。每一项智力努力都是从一个已经存在的先入为主的观念开始的，然后在进一步的探究中可以改变这个观念，并可以作为后续努力的起点。基本上，这就是汉斯·格奥尔格·伽达默尔（Hans Georg Gadamer）所称的诠释学圈（Gadamer 2004）。尽管大学里经常教授解释学，但与此同时，写作仍在继续教授——仿佛我们可以从头开始，沿着直线前进——仿佛有可能从稀薄的空气中引出一个好问题，并等待阅读，直到文学研究完成。因此，在开始写作之前决定要写些什么的看似务实、脚踏实地的建议要么是误导，要么是陈词滥调。如果它只是意味着你在把话写在纸上之前应该先想一想，那就是陈词滥调。如果这意味着你可以在沉浸于手头的话题（包括写作）之前就制定一个合理的写作计划，那就是误导。它伴随着一切：我们必须手拿笔阅读，在纸上发展思想，并建立一个不断增长的外部化思想库。我们不会被从我们不可靠的大脑中挑选出来的盲目制定的计划所引导，而是被我们的兴趣、好奇心和直觉所引导，这些兴趣、好奇心和直觉是由阅读、思考、讨论、，写作和发展想法——是不断增长并反映我们的知识和理解的东西。

通过关注有趣的内容并记录自己的智力发展，话题、问题和论点将从材料中不假思索地浮现出来。这不仅意味着找到一个主题或一个研究问题将变得更容易，因为我们不必再从头脑中的几个想法中挤出来，从我们的滑框中出现的每一个问题都会自然而然地、轻松地与材料一起工作。如果我们查看我们的滑动框，看看集群在哪里建立起来，我们不仅可以看到可能的主题，还可以看到我们已经研究过的主题——即使我们无法提前看到。没有人从零开始的想法突然变得非常具体。如果我们认真对待它并相应地工作，我们就再也不必从头开始了。

当然，那些相信自己是从零开始的人也不是真正从零开始的，因为他们也只能借鉴他们以前学到或遇到的东西。但由于他们没有根据这一事实采取行动，他们无法追溯思想的起源，手头也没有支持材料，也没有整理好思想的来源。由于写作并没有伴随他们以前的工作，他们要么从全新的东西开始（这是有风险的），要么追溯他们的想法（这是无聊的）。

由于正确的笔记很少被教授或讨论，难怪几乎所有的写作指南都建议从“头脑风暴”开始。如果你没有一路写作，大脑确实是唯一可以求助的地方。就其本身而言，这并不是一个很好的选择：既不客观也不可靠——这是学术或非小说写作中两个相当重要的方面。将头脑风暴作为一个起点的推广更令人惊讶，因为它不是大多数想法的起源：你应该通过头脑风暴在头脑中找到的东西通常没有它们的起源。相反，他们来自外部：通过阅读、讨论和倾听他人的意见，通过所有本可以伴随甚至可以通过写作改进的事情。在你写作之前思考该写些什么的建议来得太早也太迟。太晚了，因为当你面对白纸或空白屏幕时，你已经错过了建立书面资源的机会，但也太早了，如果你试图推迟每一个严肃的内容相关的工作，直到你对这个话题做出决定。

如果某件事情同时出现得太早和太迟，就不可能通过重新安排顺序来解决它，因为虚构的线性本身就是问题。聪明地记笔记是打破线性秩序的先决条件。如果你根据写作不是一个线性过程，而是一个循环过程这一事实来组织你的工作流程，那么有一个可靠的迹象：找到一个主题的问题被太多的主题所取代。找不到正确的话题是严重依赖大脑局限性的错误尝试的症状，而不是大多数研究指南暗示的不可避免的有问题的起点。另一方面，如果你在写作中发展你的思维，开放性问题将变得清晰可见，并为你提供大量可能的主题，以便在写作中进一步阐述。
	
 
在与学生们合作多年后，我确信这些学习指南试图将非线性过程（如写作）压缩成线性顺序，这是他们承诺要解决的问题和挫折的主要原因。如果你认为你必须在做研究、阅读和了解某件事之前就决定一个话题，你怎么能不找不到问题呢？如果你手边没有任何东西可以填满，你怎么能不被一张空白的纸所威胁呢？如果你发现自己被一个你盲目决定的话题困住了，而现在又不得不在最后期限临近的时候坚持下去，谁会责怪你的拖延呢？当学生们没有被教导如何将数月或数年的阅读、讨论和研究转化为他们真正可以使用的材料时，他们会被写作作业压得喘不过气来，这怎么会让人感到惊讶呢？

这些研究指南在写作作业之前忽略了一切，有点像财务顾问，他们讨论65岁的人如何为退休储蓄。在这一点上，你最好抑制自己的热情（这正是德国最常出售的研究指南之一所建议的：首先，降低对质量和洞察力的期望）\[16\]

但是那些已经通过写作发展了思维的人可以专注于他们目前感兴趣的事情，并通过做他们最喜欢做的事情来积累大量的材料。这些材料将围绕他们最常回答的问题，这样他们就不会有偏离自己兴趣太远的风险。如果你第一次选择的主题没有那么有趣，你只需继续，你的笔记会围绕着其他东西。也许你甚至会记下第一个问题不有趣的原因，并将其转化为一个足以公开的见解。当你最终决定写什么的时候，你已经做出了决定——因为你在这一过程中的每一步都做出了决定，每天一次又一次，并逐步改进。与其把时间花在寻找正确的话题上，不如把时间花在你已经存在的兴趣上，做一些必要的事情来做出明智的决定——阅读、思考和写作。通过做这些工作，你可以相信有趣的问题会出现。你可能不知道你会在哪里结束（你也不需要知道），但无论如何，你不能强迫自己洞察一个预先设想的方向。你可以最大限度地降低对你曾经选择的话题失去兴趣的风险，以及不得不重新开始的风险。

尽管学术写作不是一个线性的过程，但这并不意味着你应该遵循一种随大流的方法。相反，清晰可靠的结构至关重要。

