# 让工作推动你前进 {#wind-8}

你可能还记得学校里的（能）反应和（能）反应的区别。在第一种情况下，你需要不断地增加能量来保持这个过程。在第二种情况下，反应一旦触发，就会自行继续，甚至释放能量。工作的动力没有那么大的不同。有时我们觉得我们的工作正在消耗我们的精力，只有我们投入越来越多的精力，我们才能向前迈进。但有时恰恰相反。一旦我们进入工作流程，就好像工作本身获得了动力，推动我们前进，有时甚至激励我们。这就是我们正在寻找的动态。

一个好的工作流程可以很容易地转变为一个良性循环，在这个循环中，积极的经验激励我们轻松地承担下一个任务，这有助于我们更好地完成我们正在做的事情，这反过来使我们更有可能享受工作，等等。但是，如果我们总是觉得自己被困在工作中，我们就会变得缺乏动力，更容易拖延，从而减少积极甚至糟糕的经历，比如错过最后期限。我们可能会陷入失败的恶性循环（参见Fishbach、Eyal和Finkelstein，2010）。

任何用外部奖励欺骗自己的尝试（比如在完成一章后做一些好事）都只是短期的解决方案，不可能建立积极的反馈循环。这些都是非常脆弱的动机结构。只有当工作本身变得有回报时，动机和回报的动力才能自我维持并推动整个过程向前发展（DePasque和Tricomi，2015）。

非凡成功的健身动力教练米歇尔·西格尔（Michelle Segar）利用这种动力将最顽固的教练土豆变成了运动爱好者（Segar，2015）。她将那些确实不喜欢运动但知道自己必须这样做的人纳入可持续的锻炼计划中，重点放在一件事上：创造令人满意的、可重复的运动体验。不管她的客户在做什么——跑步、散步、团队运动、健身房锻炼或骑自行车上班。唯一重要的是，他们发现了一些能给他们带来美好体验的东西，而这些体验又是他们想要的。一旦她的客户发现了什么，他们就会受到足够的鼓励去尝试其他的东西。他们进入了一个良性循环，不再需要意志力，因为他们无论如何都想这样做。如果他们试图通过在沙发上看电视的放松夜晚来欺骗自己进行锻炼，那么他们很快就会径直走向沙发，完全跳过锻炼，因为我们就是这样做的。

反馈回路不仅对动机的动态性至关重要，也是任何学习过程的关键因素。没有什么比在工作中变得更好的经历更能激励我们。在某些方面改进的唯一机会是获得及时和具体的反馈。寻求反馈，而不是回避反馈，是任何想要学习的人的第一美德，或者用心理学家卡罗尔·德威克更一般的话说，是想要成长的人的第一美德。德威克令人信服地表明，长期成功最可靠的预测因素是“成长心态”。积极寻求和欢迎反馈，无论是正面的还是负面的，是长期成功（和幸福）的最重要因素之一。相反，没有什么比“固定心态”更能阻碍个人成长。那些害怕并避免反馈的人，因为反馈可能会损害他们珍视的积极自我形象，短期内可能感觉更好，但实际表现会很快落后（Dweck 2006；2013）。具有讽刺意味的是，因此往往是那些天赋异禀、才华横溢的学生，他们受到了很多赞扬，他们更容易形成固定的思维模式并陷入困境。他们因自己的才干（天赋）而受到表扬，而不是因为自己的工作而受到表扬，他们倾向于保持这种印象不变，而不是让自己面临新的挑战和从失败中学习的可能性。拥抱成长心态意味着从向好的方向改变中获得快乐（这主要是内在的回报），而不是从被表扬中获得快乐（这是外在的回报）。对后者的定位使人坚持到安全、可靠的区域。朝向第一个的方向使人们注意到最需要改进的领域。寻求尽可能多的学习机会是最可靠的长期增长战略。如果说成长和成功还不够理由的话，那么对失败的恐惧可能是所有恐惧症中最丑陋的一个名字：恐惧症。

拥有增长心态是至关重要的，但这只是等式的一个方面。同样重要的是，建立一个能够以实际方式实现反馈循环的学习系统。如果你能得到的唯一反馈是对你已经完成的工作每隔几个月一次，那么公开接受反馈并没有多大帮助。学术写作的线性模型几乎没有反馈机会，甚至反馈机会通常也会随着时间的推移而分散（vgl.Fritzsche，Young und Hickson，2003）。如果你为论文选择一个主题，并根据线性模型进行工作，那么只有在经过多个阶段的研究后，你的选择是明智的，你才能学会。这同样适用于你是否理解你所读的内容，以及你的观点是否合理的问题。

另一方面，遵循循环方法可以实现许多反馈循环，这给了您在工作中改进工作的机会。这不仅仅是为了增加学习的机会，也是为了能够纠正我们不可避免的错误。由于反馈循环通常比最后的一大块反馈要小，因此它们也不那么可怕，更容易接受。

举个例子，拿支笔阅读，迫使我们思考我们所读的内容并检查我们的理解。这是最简单的测试：我们倾向于认为我们理解了所读的内容——直到我们试图用自己的话重写它。通过这样做，我们不仅能更好地了解自己的理解能力，还能提高清晰、简洁地表达理解的能力——这反过来有助于更快地掌握想法。如果我们试图在这里愚弄自己，写下无法理解的单词，我们将在下一步中发现它，当我们试图将我们的文学笔记变成永久性的笔记，并试图将它们与他人联系起来。

用自己的语言表达理解的能力是每个写作人的基本能力——只有在意识到自己缺乏理解的情况下这样做，我们才能在写作方面做得更好。但是，我们做得越好，记笔记就越容易、越快，这又增加了学习经验的数量。这同样适用于区分文本中重要部分和次要部分的关键能力：我们做得越好，我们的阅读就会越有效，我们能读的越多，我们学到的越多。我们将进入一个美丽、良性的能力循环。你会情不自禁地被它所激励。

写永久性笔记也是如此，它还有一个内置的反馈回路：用书面表达我们自己的想法会让我们意识到我们是否真的仔细思考了它们。当我们试图将它们与之前的书面笔记结合起来时，系统将毫不含糊地向我们展示矛盾、不一致和重复。虽然这些内置的反馈回路不会使来自同事或主管的反馈变得多余，但它们是唯一“始终可用”的回路，可以帮助我们每天改进一点、多次。最好的一点是，当我们学习并变得更好的时候，我们的滑箱也变得更有知识。它成长和提高。它增长得越多，就越有用，我们就越容易建立新的联系。

滑动框不是一组注释。使用it与其说是检索特定的笔记，不如说是指向相关的事实，并通过让想法混合而产生见解。它的可用性随着它的大小而增长，不仅是线性增长，而且是指数增长。当我们转向滑箱时，它的内在联系将不仅为我们提供孤立的事实，而且为我们提供发展的思路。此外，由于其内在的复杂性，一个搜索引擎认为滑动框会让我们面对我们没有寻找的相关笔记。这是一个非常显著的差异，随着时间的推移，它变得越来越重要。它包含的内容越多，可以提供的连接就越多，以智能方式添加新条目和接收有用建议就越容易。

就相互联系而言，我们的大脑工作方式并没有那么不同。心理学家过去认为大脑是一个有限的存储空间，它会慢慢填满，使人在晚年更难学习。但我们今天知道，我们已经拥有的关联信息越多，学习就越容易，因为新信息可以与该信息对接。是的，我们学习孤立事实的能力确实有限，而且可能会随着年龄的增长而下降。但如果事实不是孤立的，也不是以孤立的方式学习的，而是在一个思想网络或“心理模型的格子”（Munger，1994）中联系在一起，那么理解新信息就变得更容易了。这不仅使学习和记忆更容易，而且使以后在需要的时刻和上下文中检索信息更容易。

因为我们是所有笔记的作者，所以我们在学习的过程中与滑盒保持一致。这是与使用维基百科这样的百科全书的另一大区别。我们在大脑中使用的思维模式、理论和术语与在滑箱中一样。滑箱产生了过多的可能性，这使它能够给我们带来惊喜，激励我们产生新的想法，进一步发展我们的理论。不仅仅是滑箱或我们的大脑，而是它们之间的动态使使用它变得如此高效。
