# 阅读理解 {#wind-10}

```
“我建议你手里拿着笔阅读，在一本小书中写下你认为常见或有用的东西的简短提示；因为这将是在你的记忆中留下这样的记忆的最好方法。”-本杰明·富兰克林\[26\]
```


## 拿着钢笔看书

要写出一篇好的论文，你只需要重写一篇好的草稿；要写出一份好的草稿，你只需要把一系列的笔记变成连续的文本。由于一系列的笔记只是对你的滑纸盒中已有的笔记进行重新排列，你真正需要做的就是在阅读时手里拿着一支笔。

如果你理解了你所读的内容，并将其翻译成你自己思想的不同背景（在滑框中具体化），你就不得不将他人的发现和想法转化为新的、你自己的东西。它是双向的：滑盒中的一系列笔记发展成论点，这些论点是由你头脑中的理论、想法和心理模型形成的。你头脑中的理论、想法和思维模式也会被你读到的东西所塑造。他们不断变化，并受到滑箱所面临的令人惊讶的联系的挑战。滑箱越丰富，你自己的想法就越丰富。滑箱是一个想法发生器，与你自己的智力发展同步发展。总之，你可以把以前分离的事实，甚至是孤立的事实，转化为相互关联的思想的临界质量。

从滑框到最终文本的步骤非常简单。内容已经很有意义，经过深思熟虑，并且在许多部分已经被放进连接良好的序列中。这些笔记只需按线性顺序排列即可。虽然这些注释本身是为了便于自己理解而制定的，但它们同时嵌入到一个或多个丰富其含义的上下文中。从滑动框中绘制草图更像是与之对话，而不是机械动作。因此，结果绝不是以前工作的复制品，而是总是伴随着惊喜。总会有一些你无法预料的事情。显然，这同样适用于之前的每一步。手握笔阅读的结果也无法预料，在这里，我们的想法也不是抄袭，而是与我们阅读的文本进行有意义的对话。

当我们从文本的特定语境中提取思想时，我们处理的思想在特定语境中为特定目的服务，支持特定论点，是不是我们的理论的一部分，或者是用我们不会使用的语言编写的。这就是为什么我们必须将它们翻译成我们自己的语言，以便将它们嵌入到我们自己思维的新语境中，即滑框中的不同语境中。翻译意味着用不同的词语尽可能真实地描述原作，但这并不意味着可以自由地制作适合自己的作品。同样，仅仅是抄袭引语几乎总是通过断章取义来改变它们的含义，即使词语没有改变。这是一个初学者常见的错误，它只会导致想法的拼凑，而不会导致连贯的想法。

虽然文献注释将与书目详细信息一起存储在参考系统中，与滑动框分开，但仍接近原文的上下文，但它们的书写已经着眼于滑动框内的思路。Luhmann将此步骤描述如下：“我手边总是有一张纸条，上面我记下了某些页面的想法。在背面我写下了书目细节。写完这本书后，我仔细阅读了我的笔记，并思考这些笔记如何与纸条盒中已经写好的笔记相关。这意味着我阅读时总是着眼于可能的错误。”滑动盒中的连接。”（Luhmann等人，1987，150）

文学笔记的广度实际上取决于文本以及我们需要它做什么。这还取决于我们简洁的能力、文本的复杂性以及理解的难度。由于文学笔记也是理解和掌握文本的工具，因此在更具挑战性的情况下，更详细的笔记是有意义的，而在更简单的情况下，只记下一些关键词就足够了。Luhmann当然是一个外行，他满足于非常简短的笔记，并且仍然能够在不扭曲原文含义的情况下将它们转换成有价值的便笺盒笔记。\[27\]这主要是因为在我们的头脑中有一个广泛的心理模型或理论晶格，使我们能够快速识别和描述主要思想（参见Rickheit和Sichelschmidt，1999）。每当我们探索一个新的、不熟悉的主题时，我们的笔记往往会更广泛，但我们不应该对此感到紧张，因为这是一种我们不能跳过的有意识的理解练习。有时我们有必要慢慢地阅读一篇困难的课文，有时甚至可以把整本书简化成一句话。唯一重要的是，这些注释为下一步提供了最好的支持，即编写实际的滑箱注释。最有帮助的是反思我们阅读的文本的框架、理论背景、方法论或视角。这通常意味着对未提及的内容和提及的内容进行反思。

以这种方式记录文学笔记与大多数学生记录文学笔记的方式大不相同，后者要么不够系统，要么过于系统。大多数情况下，它是以错误的方式系统化的：通过使用经常推荐的阅读技巧，如SQ3R或SQ4R，他们对待每一篇文章都一视同仁，不管内容如何。他们没有明确决定笔记的格式和组织，也没有计划在以后如何处理笔记。如果记笔记没有明确的目的，那么记笔记更像是一件琐事，而不是一个更大项目中的一个重要步骤。有时，长篇摘录是出于好意而写的，但这是不可持续的。有时候，唯一能做的事情就是在句子下面划线，并在书的边缘做一些评论，这几乎就像根本不做笔记一样。通常情况下，阅读并不伴随着做笔记，就写作而言，这几乎和根本没有阅读一样有价值。在这里，“一切”都是关于在滑动框中积累大量有用的笔记，这让我们清楚地知道如何阅读和如何做文学笔记。

虽然做文学笔记的目的和程序一样明确，但你可以自由地使用任何最有助于理解你正在阅读的内容和获得有用笔记的技巧——即使你使用十种不同颜色的下划线和SQ8R阅读技巧。但是，在你做唯一真正重要的一步之前，所有这些都只是额外的一步，那就是做一张永久的便笺，这将为实际的滑动框增加价值。你需要采取某种形式的文学笔记，捕捉你对文本的理解，这样你在写便条时眼前就有了一些东西。但不要把它本身变成一个项目。文学笔记很短，用来帮助写便条。其他一切要么有助于达到这一点，要么是分散注意力。

您可以直接在Zotero中键入一个文献注释，它将和书目详细信息一起存储在Zotero中。不过，你可能想手写。不同的独立研究表明，手写有助于理解。在一项规模虽小但引人入胜的研究中，两位心理学家试图找出，如果学生在课堂上用手记笔记或将笔记输入笔记本电脑，是否会产生影响（Mueller和Oppenheimer，2014）。在学生们能够记住的事实数量方面，他们没有发现任何差异。但是在理解讲座内容方面，那些用手做笔记的学生表现得更好。一周后，这种理解上的差异仍然可以清楚地衡量。

这没有什么秘密，解释也很简单：手写速度慢，而且无法像电子笔记那样快速更正。因为学生的写作速度不足以跟上课堂上所说的每一句话，所以他们不得不专注于所说内容的要点，而不是细节。但是要记下讲座的要点，你首先必须理解它。因此，如果你是手写，你必须思考你所听到（或读到）的东西——否则你就无法掌握基本原理、观点和论点的结构。手写使纯粹的复制变得不可能，但相反，它有助于将所说（或写）的内容翻译成自己的文字。在笔记本电脑上打字的学生要快得多，这使他们能够更仔细地复制讲稿，但却避开了实际理解。他们专注于完整性。逐字记录几乎可以不用思考就可以完成，就好像文字是从耳朵到手的捷径，绕过大脑。

如果你决定手写笔记，只需把它们放在一个地方，并按照通常的方式按字母顺序排列：“姓氏年”。然后，您可以轻松地将它们与参考系统中的书目详细信息进行匹配。但是，无论你是否手写，请记住，这都是关于本质、理解和为下一步做准备的问题——将想法转移到你自己的思维框架中。

## 虚心

虽然选择性是智能记笔记的关键，但以智能的方式进行选择性同样重要。不幸的是，默认情况下，我们的大脑在选择信息方面不是很聪明。虽然我们应该找出挑战我们思维方式的不确定论据和事实，但我们自然会被一切让我们感觉良好的事物所吸引，而这些事物都证实了我们已经相信我们知道的东西。

就在我们决定一个假设的那一刻，我们的大脑自动进入搜索模式，扫描我们周围的支持数据，这既不是学习也不是研究的好方法。更糟糕的是，我们通常甚至没有意识到这种暗中干扰我们生活的“确认偏见”（或“自我偏见”）。不知何故，我们似乎碰巧被想法相同的人包围着。（当然不是故意的。我们只是把时间花在喜欢的人身上。为什么我们喜欢他们？正确：因为他们的想法和我们一样。）我们只是碰巧读了一些倾向于证实我们已经知道的东西的出版物。（当然不是故意的。我们只是试着坚持好的、有智慧的文本。是什么让我们认为这些文本是好的、有智慧的？正确：因为它们对我们来说是有意义的。我们环顾四周，删掉不确定的事实，甚至没有注意到我们没有看到的东西，就像同一个城市一样，根据我们的心情，有一天会充满快乐的人，有一天会充满痛苦的人。

确认偏见是一种微妙但主要的力量。正如心理学家雷蒙德·尼克森（Raymond Nickerson）所说：“如果一个人试图找出人类推理中最值得注意的一个有问题的方面，那么确认偏见就必须是考虑的候选因素之一”（尼克森，1998，175）。

即使是最优秀的科学家和思想家也不例外。他们之所以与众不同，仅仅是因为他们意识到这个问题并采取了一些措施。查尔斯·达尔文是典型的榜样。他强迫自己写下（并因此详细阐述）对他的理论最具批判性的论点。“我有\[…\]多年来，我遵循一条金科玉律，即每当我遇到一个公布的事实，一个与我的一般结果相反的新的观察结果或想法时，一定要立即将其记录下来；因为根据经验，我发现这些事实和想法更容易从记忆中消失，而不是从有利的记忆中消失由于这个习惯，很少有人反对我的观点，我至少没有注意到，也没有试图回答。”（达尔文1958，123）

这是一种处理确认偏差的好方法（主要是心理上的）。但我们正在寻找在外部系统中洞察我们心理局限性的方法。我们希望做出正确的决定，而不需要太多的脑力劳动——就像奥德修斯一样，他把自己绑在船的桅杆上，让自己无法跟随诱惑人的汽笛声。有了一个好的系统，仅仅是工作流程的必要性就可以迫使我们在不需要变得更加道德的情况下更为谨慎地行事。这里通过两个步骤来解决确认偏见：第一，将整个写作过程颠倒过来；第二，将动机从寻找确认事实转变为不加区分地收集任何相关信息，而不管它支持什么论点。

大多数研究指南所提倡的线性过程，疯狂地从关于假设或写作主题的决定开始，是让确认偏见猖獗的可靠途径。首先，你基本上把你现在的理解作为结果，而不是把它作为起点，让自己陷入片面的认知。然后，你人为地在完成事情（为你的先入为主的论点找到支持）和产生见解之间制造利益冲突，把任何偏离你先入为主的计划变成对你自己项目成功的反叛。这是一条很好的经验法则：如果洞察力对你的学术或写作成功构成威胁，那你就是做错了。

自下而上而不是自上而下地发展论点和想法，是打开自己的视野的第一步，也是最重要的一步。我们应该能够专注于我们遇到的最有洞察力的想法，并欢迎最令人惊讶的事件转变，而不损害我们的进展，甚至更好，因为它推动了我们的项目向前发展。我们推迟了关于具体写什么的决定，并专注于在滑动框内建立临界质量。我们不想一直牢记这一假设，而是想：

```
·确认我们已将任务分开，并专注于理解我们阅读的文本，确保我们对其内容进行了真实描述
```

```
·找到它的相关性并建立联系。
```

只有到那时，我们才后退一步，看看发展了什么，然后决定从中得出什么结论。

滑动框迫使我们在阅读和记笔记时要有选择性，但唯一的标准是，滑动框中的讨论是否增加了内容。唯一重要的是它连接或开放连接。任何东西都可以在滑箱中促进思想的发展：一个补充和一个矛盾，一个看似显而易见的想法的质疑，以及一个论点的区别。我们所寻找的事实和信息可以增加一些东西，从而丰富我们的资料。在开始使用滑箱时，最重要的习惯性变化之一是将注意力从带有我们先入为主想法的单个项目转移到滑箱内的开放连接上。

在调整了我们的利益之后，我们可以更进一步，为寻找不确定的事实做好准备。只收集片面的想法不会很丰富。是的，我们必须有选择性，但不是在正反两方面，而是在相关或无关方面。一旦我们关注到滑箱的内容，不确认的数据突然变得非常有吸引力，因为它在滑箱中打开了更多可能的连接和讨论，而仅仅确认数据并不能。通过练习，寻找不确定的数据变得更容易，并且会变得非常上瘾。一条信息如何改变对某个问题的整体看法的经验是令人兴奋的。滑箱的内容越多样化，它就越能推动我们的思维向前发展——前提是我们还没有确定前进的方向。可以在后续说明中甚至在期末论文中讨论滑动框内的矛盾。从一场充满正反两面的生动讨论中写出一篇有趣的文章要比从一堆片面的笔记和看似恰当的引语中写出一篇有趣的文章容易得多。事实上，如果它仅仅基于我们在详细阐述问题之前能够提前提出的想法，那么几乎不可能写出任何有趣的、值得发表的东西（从而激发人们的灵感）。

滑动框对于它所输入的内容是相当不可知的。它只喜欢相关的笔记。在阅读和收集相关数据、连接思想并讨论它们如何结合之后，是时候得出结论并为论点建立线性结构了。

## 明白要点

区分相关信息和不太相关信息的能力是另一种只能通过实践来学习的技能。这是寻找要点并将其与仅仅支持细节区分开来的实践。当我们手里拿着笔阅读和写一个又一个永久性的笔记时，我们被迫做出这种区分，这不仅仅是练习：它是一天重复多次的有意练习。对于学者来说，提取一篇文章或一个想法的要点并以书面形式进行说明，就像钢琴师的日常钢琴练习一样：我们练习的频率越高，注意力越集中，我们就变得越有道德。

帮助我们导航文本和话语的模式不仅是理论、概念或各自的术语，而且是我们自动扫描论点的典型错误，我们应用的一般类别，写作风格表明我们从不同的见解中学习或发展的某种思想流派或心智模式，可以像一套伟大且不断增加的思维工具一样收集。没有这些工具和参考点，就不可能有专业的阅读或理解。我们会以同样的方式阅读每一篇文章：就像一本小说。但有了学会的识别模式的能力，我们就可以进入技巧圈：阅读变得更容易，我们更快地掌握要点，可以在更短的时间内阅读更多内容，并且可以更容易地识别模式并提高我们对模式的理解。在此过程中，我们增加了一套思维工具，这不仅有助于学术工作，而且有助于思维和理解。这就是为什么伯克希尔哈撒韦公司副董事长查理·芒格（Charlie Munger）将其描述为一个拥有广泛工具并知道如何应用这些工具的世故人士。

但是，只有当我们自己有意识地决定承担阅读的任务并对其进行选择时，这种动力才能开始，而这只能依靠我们自己对什么重要什么不重要的判断。教科书或中学文学一般都无法摆脱这一点，而仅仅依靠教科书或中学文学的学生没有机会成为“世故的智者”。这与哲学家伊曼纽尔·康德（Immanuel Kant）在其关于启蒙运动的著名著作中所描述的“未成年”（未成年）并不遥远就是不能在没有他人指导的情况下运用自己的理解力。如果原因不是缺乏理解力，而是犹豫不决和缺乏勇气在没有他人指导的情况下运用自己的思想，那么这个未成年人就是自我强加的。敢于知道！（萨佩雷·奥德）因此，启蒙运动的座右铭是“有勇气运用自己的理解力。”

我建议从字面上理解。运用自己的理解能力是一种挑战，而不是一种天赋。卢曼强调在这方面永久性说明的重要性：

```
“阅读学术文本的问题似乎在于，我们不需要短期记忆，而是需要长期记忆来建立参考点，以区分重要和不重要的东西，区分新信息和重复信息。当然，要记住一切是不可能的。那将是死记硬背的学习。换言之：一个人必须非常有选择性地阅读，并提取广泛和相关的参考资料。一个人必须能够跟踪复发。但如果指导是不可能的，如何学习呢？[…]也许最好的方法是做笔记——不是摘录，而是对一篇课文进行精简的重新编排。重写已经写好的内容几乎会自动训练一个人将注意力转移到观察中的框架、模式和类别，或条件/假设上，这可以实现某些描述，但不能实现其他描述。总是问这样一个问题是有道理的：什么是没有意义的，如果提出了某种主张，什么是被排除在外的？如果有人说"人权",有什么区别?？对“非人权”和“人类义务”的区分是一种文化比较，还是与一些没有人权概念但生活在一起的历史人物的比较？通常，文本并没有给出这个问题的答案或明确的答案。但是，我们必须依靠自己的想象力.” (Luhmann 2000, 154f)
```

你做得越好，你就可以越快地记下笔记，这仍然很有帮助。卢曼的笔记非常简洁（施密特2015）。通过实践，我们可以找到合适的词语，以尽可能最好的方式表达某件事，也就是说，用一种简单但不简单的方式。你的文章的读者不仅会欣赏你清晰地解释某事的能力，与你交谈的人也会受益于这种能力，因为它不仅限于写作。它延伸到说话和思考。事实证明，读者认为作者和听众以及演讲者越聪明，他们的表达就越清晰、越切题（Oppenheimer，2006）。

识别模式、质疑所使用的框架和发现他人的区别的能力，是批判性思考和审视文本或谈话主张背后的先决条件。能够重新构建问题、论断和信息比拥有广泛的知识更重要，因为没有这种能力，我们就无法将我们的知识用于实践。好消息是这些技能是可以学习的。但这需要深思熟虑的实践（爱立信、克拉姆普和特施-罗默1993年；安德斯-爱立信2008年）。巧妙地记笔记是对这些技能的刻意练习。仅仅阅读、在句子下面划线并希望记住内容是不够的。

## 学会阅读

```
“如果你说不清楚，你自己也不明白.” (John Searle)
```

物理学家、诺贝尔奖获得者理查德·费曼（Richard Feynman）曾说，他只有在做介绍性演讲时才能确定自己是否理解某件事。手里拿着笔看书，是一种小规模的演讲。永久性音符也面向那些不了解文本背后思想、不了解原始语境、只具备该领域一般知识的听众。唯一不同的是，这里的观众是由我们未来的自己组成的，他们很快就会达到与从未接触过我们所写内容的人一样的无知状态。当然，让其他人参与写作过程的各个阶段是有帮助的，因为这样我们就可以从他们的脸上看到我们做得有多好，或者我们的论点有多有说服力，但这是不切实际的。

此外，我们不应该低估写作的优势。在口头陈述中，我们很容易摆脱毫无根据的说法。我们可以用自信的手势来分散争论的间隙，或者随便说一句“你知道我的意思”，不管我们是否知道我们的意思。在书面上，这些策略有点太明显了。检查这样的陈述很容易：“但这就是我所说的！”写作最重要的优点是，当我们不理解某些东西时，它可以帮助我们面对自己，而我们不相信这些东西。

费曼在一次对年轻科学家的演讲中强调：“原则是你不能愚弄自己，你是最容易被愚弄的人。”。阅读，尤其是重读，很容易让我们误以为我们理解了一篇文章。重读是特别危险的，因为仅仅是曝光效应：当我们熟悉某件事的时候，我们开始相信我们也理解了它。除此之外，我们也更喜欢它（Bornstein 1989）。

虽然很明显，熟悉不是理解，但在我们以某种形式测试自己之前，我们没有机会知道我们是否理解某些东西，或者只是相信我们理解某些东西。如果我们不在学习中验证我们的理解，我们会很高兴地享受变得更聪明、知识更渊博的感觉，而事实上却像我们一样保持沉默。当我们试图用自己的文字解释我们读到的东西时，这种温暖的感觉很快就消失了。突然，我们发现了问题所在。试图用我们自己的话来重新表述一个论点，这让我们毫不留情地面对我们理解上的所有差距。当然感觉不太好，但这场斗争是我们提高理解、学习和前进的唯一机会（参见下文）。这也是有意的做法。现在我们面临着一个明确的选择：我们必须在感觉更聪明还是变得更聪明之间做出选择。虽然写下一个想法感觉像是一条弯路，但花额外的时间，不写下来是真正的浪费时间，因为这会使我们读到的大部分内容无效。

理解不仅仅是学习的先决条件。从某种程度上说，学习就是理解。其机制也没有什么不同：我们只有通过测试自己的进步才能提高我们的学习。在这里，重读或复习也不会让我们面对我们尚未学到的东西，尽管它让我们感觉我们已经学到了。只有真正尝试检索信息才能清楚地告诉我们是否学到了一些东西。仅仅是曝光效应也会愚弄我们：看到我们以前见过的东西会引起同样的情绪反应，就好像我们能够从记忆中提取信息一样。因此，重读让我们觉得我们已经学到了我们所读到的：“我已经知道了！”在这方面，我们的大脑是可怕的老师。在这里，我们面临着两种选择，一种是让我们感觉自己学到了什么，另一种是让我们真正学到了什么。

如果你现在想：“那太荒谬了。谁会想读书，假装学习只是为了学习和理解的幻觉？”请查阅统计数据：大多数学生选择每天不以任何方式测试自己。相反，他们应用研究再次证明的方法（Karpicke、Butler和Roediger，2009年）和（Brown，2014年，第1章）几乎完全没有用处：重读句子并在下面划线，以便以后重读。他们中的大多数人选择了这种方法，即使他们被教导他们不工作。有意识地，我们可能都会选择相同的，但真正重要的是，我们每天都要做出许多小的、隐含的选择，而这些选择往往是无意识地做出的。

这就是为什么选择一个外部系统，迫使我们深思熟虑地练习，并让我们尽可能多地面对我们缺乏理解或尚未学到的信息是如此明智的举动。我们只需要做一次有意识的选择。

## 通过阅读学习

学习本身需要深思熟虑的实践，我指的是帮助我们增进对世界理解的实际学习，而不仅仅是让我们通过考试的学习。深思熟虑的实践是需要的；这需要努力。试图跳过这一步就像去健身房，尽可能少的努力去锻炼。这是没有道理的，就像雇一个教练来做举重是没有道理的。教练不是来做这项工作的，而是向我们展示如何以最有效的方式利用我们的时间和精力。我们刚刚开始意识到，在体育运动中不言而喻的是，学习也是如此。Doyle（2008，63）写道：“做工作的人就是学习的人。”。很难相信，但在教育领域，这仍然是一个革命性的想法。

学习需要努力，因为我们必须思考才能理解，我们需要积极地检索旧知识，以说服我们的大脑将其与新思想联系起来作为线索。要理解这一想法的突破性，有助于记住教师在通过预先整理信息、将信息分类为模块、类别和主题，使学生更容易学习方面仍付出了多少努力。通过这样做，他们实现了与他们打算做的相反的结果。他们让学生更难学习，因为他们把所有东西都安排好复习，剥夺了建立有意义的联系的机会，也剥夺了通过将其翻译成自己的语言来理解事物的机会。它就像快餐：既没有营养，也不是很享受，只是方便而已。

如果老师在课中改变话题，在任何人都有机会真正理解第一个话题之前，只会回到后面的话题，这将是令人惊讶的。经常对学生进行测试也是出人意料的，有一半的时间是关于那些还没有提到的事情。但这可能会让学生们感到恼火，因为他们习惯于将自己的材料按整齐的类别呈现，这将迫使他们理解自己所遇到的情况——这将使他们真正学会。

```
“变异、间隔、引入语境干扰、使用测试而不是演示作为学习事件等操作都具有在学习过程中阻碍学习的共同特点，但它们通常会通过培训后的保留和迁移测试来增强学习。相反，在教学或培训过程中，诸如保持条件恒定、可预测以及对给定任务进行大量试验等操作通常会提高学习速度，但通常无法支持长期保留和迁移” (Bjork, 2011, 8).
```

当我们试图在知道如何回答之前回答一个问题时，我们以后会更好地记住答案，即使我们的尝试失败了（Arnold和McDermott 2013）。如果我们努力尝试检索信息，从长远来看，我们更有可能记住它，即使我们最终在没有帮助的情况下检索不到它（Roediger和Karpicke，2006）。即使没有任何反馈，如果我们试着自己记住一些东西，我们也会过得更好（Jang等人，2012年）。经验数据相当明确，但这些学习策略并不一定感觉正确。直觉上，大多数学生都会采取填鸭式的学习方式，这只是一个又一个术语，用来反复阅读某件东西，但学习失败（Dunlosky et al.2013）。尽管重读对学习没有帮助，但对理解肯定没有帮助。诚然，填鸭式学习确实能让你的大脑在短时间内记住信息——通常足够长的时间呆在那里通过考试。但是死记硬背不会帮助你学习。正如Terry Doyle和Todd Zakrajsek所说：“如果学习是你的目标，那么填鸭式学习是一种非理性行为”（Doyle和Zakrajsek，2013）。\[29\]

与其复习课文，不如打一轮乒乓球。事实上，锻炼很可能会对你有更大的帮助，因为锻炼有助于将信息转化为长期记忆（参见Ratey 2008）。此外，锻炼可以减少压力，这是好事，因为压力会让我们的大脑充斥着抑制学习过程的激素（Baram等人，2008）。

简言之：纯粹的重新审视对理解和学习都没有任何意义。我们甚至可以称之为学习，这是有争议的。

因此，研究得最好、最成功的学习方法是精化，这并不奇怪。这与我们做聪明笔记并将其与他人结合时的做法非常相似，这与仅仅重新审视（Stein et al.1984）相反。精化只意味着真正思考我们阅读的内容的意义，它如何告知不同的问题和主题，以及它如何与其他知识结合。事实上，“为学习而写作”是“精化方法”（Gunel、Hand和Prain，2007年）的名称。但有一个警告。尽管精化可以很好地进行深入理解，但如果您只想了解孤立的百科全书事实，它可能不是最佳选择（Rivard 1994）。但是，只要你不想成为一名智力竞赛节目的候选人，你为什么要这样做呢？滑动框负责存储事实和信息。思考和理解是你无法摆脱的，这就是为什么专注于这部分工作是有意义的。它也有利于学习，这是一个很好的副作用。Luhmann几乎从未读过两次文本（Hagen，1997年），并且仍然被认为是一个令人印象深刻的对话伙伴，他似乎掌握了所有信息。\[30\]

因此，使用滑箱并不意味着将信息存储在滑箱中，而不是存储在大脑中，即不学习。相反，它有助于真正的长期学习。这只是意味着不要把孤立的事实塞进你的大脑——这可能是你无论如何都不想做的事情。因此，有人反对说，记笔记和把笔记分类放进邮箱需要花太多时间，这是短视的。写作、记笔记和思考想法之间的联系正是需要学习的精化。不从我们读到的东西中学习，因为我们没有花时间详细阐述它，这是真正的浪费时间。

大脑和滑盒之间有着明确的分工：滑盒负责细节和参考资料，是一种长期记忆资源，客观上保持信息不变。这使大脑能够专注于要点、更深层次的理解和更大的图景，并将其释放出来进行创新。大脑和滑箱都能专注于他们最擅长的事情。
