# 你需要做的一切 {#wind-13}

```
“写作本身会让你意识到事物中的漏洞。直到看到我写的东西，我才知道我在想什么。所以我相信，即使你是一个乐观主义者，当你坐下来构思一个故事、一个段落或一个句子时，你的分析部分也会起作用。你会想，‘哦，那不可能是对的。’你必须回去，你必须重新考虑这一切。” (Carol Loomis)[37]
```

由于写作无非是对草稿的修改，无非是将一系列注释转化为连续的文本，这些文本每天都在写，并在滑动框中连接和索引，因此无需担心找到写作主题。只要看看你的滑动框，看看集群是在哪里建立起来的。这些集群一次又一次地吸引了你的兴趣，所以你已经知道你已经找到了可以使用的材料。现在你可以在你的桌面上展开这些笔记，或者使用Zettelkasten的大纲视图，概述你的论点，并构建一个章节或段落的初步顺序。这将使未回答的问题变得明显，并将显示论点中需要填补的空白，并显示出哪些部分仍需要一些工作。

另一次，视角发生了变化：现在，它不是关于在另一位作者的论点的上下文中理解某些东西，也不是关于在滑动框中寻找多个连接，而是关于发展一个论点并将其纳入手稿的线性。现在的问题不是拓宽视角，找到尽可能多的思路，让一个想法发挥作用，而是缩小视角，只就一个主题做出决定，删掉所有不直接有助于文本发展和支持主要论点的内容。

## 从头脑风暴到滑箱风暴

```
“记住这一课：“一个想法或一个事实的价值不仅仅是因为你很容易获得。”” (Charles T. Munger)
```

每当有人在努力寻找一个好的话题来写的时候，其他人会建议进行头脑风暴。尽管1919年亚历克斯·奥斯本（Alex Osborn）对其进行了描述，并于1958年在查尔斯·哈奇森·克拉克（Charles Hutchison Clark）的《头脑风暴：创造成功想法的动态新方式》（Brainstorming:the Dynamic New Way to Create Successful Idea）一书中向更广泛的读者介绍了它，但它仍然具有现代的声音。对许多人来说，这仍然是产生新想法的最佳方法。我建议将其视为对大脑的过时固定的表达，这反映在我们的教育系统对用心学习的固定中——这意味着在没有外部工具的情况下思考。测试学生的记忆知识并不能很好地说明他们的理解能力，而有人在头脑风暴会议上提出了很多想法这一事实也不能很好地说明他们的素质。

当我们想找到重要、有趣、可以利用现有材料处理的话题时，大脑会优先考虑那些当下容易获得的想法。显然，这并不等于相关。大脑更容易记住最近遇到的信息，这些信息带有情感，并且生动、具体或具体。理想情况下，它也会押韵（参见Schacter，2001；Schacter，Chiao和Mitchell，2003）。一切相当抽象、模糊、情感中立或甚至听起来不好的东西都远远不在优先事项之列——这并不完全是智力努力的最佳标准。

更糟糕的是，我们倾向于最喜欢我们最初的想法，并且非常不愿意放弃它们，不管它们的实际相关性如何（Strack和Mussweiler，1997）。在你开始思考通过召集一群朋友一起集思广益来克服集思广益的局限性是否是一个好主意之前，忘掉它吧：集思广益小组中的更多人通常会提出一些不太好的想法，并在不经意间将自己限制在一个较窄的话题范围内（马伦、约翰逊和萨拉斯1991）。\[38\]

但是，对于那些将写作视为独立于其他人的任务的人来说，找到合适的写作主题是一个很大的问题，而对于我们这些使用滑箱的人来说，这不是一个问题。那些依靠大脑的人会先问自己，然后问他们的上司：我读了这么多书，但我应该写些什么呢？另一方面，我们这些已经以一种聪明的方式伴随着我们的研究写作和收集笔记的人，不再需要头脑风暴了。我们可以直接查看我们的保险箱。如果我们以前有一个好主意（当然，我们更有可能在几个月内而不是几分钟内想出一个好主意），它就会在那里。它甚至可能已经证明自己值得跟进，在这种情况下，它已经连接到支持材料。看到什么起作用比预测什么可能起作用要容易得多。

我们不需要担心写什么的问题，因为我们已经回答了这个问题——每天多次。每次我们读到一些东西，我们都会决定哪些东西值得写下来，哪些不值得。每次我们做一个永久性的笔记，我们也会对我们认为与我们的长期思考和思想发展相关的文本的各个方面做出决定。我们不断明确想法和信息是如何相互联系的，并将它们转化为笔记之间的文字联系。通过这样做，我们开发出可见的思想集群，这些思想现在可以转化为手稿。

这个过程是自我强化的。一个明显发展的集群吸引了更多的想法，提供了更多可能的联系，这反过来会影响我们对阅读和思考内容的选择。它们成为我们日常工作的路标，引导我们去思考值得思考的事情。主题自下而上发展，并在发展过程中获得吸引力。一旦滑箱增长了一点，我们就可以用务实的眼光来看待滑箱，取代我们对有趣的东西和我们认为相关的东西的想法，在那里我们可以清楚地看到真正有趣的东西，以及我们在哪里找到了可以使用的材料。

正是一开始的决定，使写作成为整个智力活动的手段和终点，彻底改变了主题发现的角色。现在不再是找一个话题来写，更多的是通过写作来解决我们产生的问题。

通过在日常工作中提出问题，我们将大数定律带到了我们这边。事实上，很少有问题适合在一篇文章、一篇论文或一本书中回答。有些过于宽泛，有些过于狭隘，有些无法用我们能够合理获得的知识来回答，但对大多数人来说，我们只是没有材料来处理。那些一开始就有计划、有想法要写什么的人可能会在途中的某个地方遇到这个事实。然后，他们可能会纠正一个不幸的选择一两次，但必须坚持他们在某一点上所选择的，否则他们将永远无法完成他们的项目。

另一方面，如果我们让问题从滑动框中产生，我们知道这些问题在数十个甚至数百个其他可能的问题中被尝试和测试。绝大多数问题可能很快就得到了回答，或者由于缺乏兴趣或缺乏材料，没有对它们进行注释而消失。进化就是这样运作的：通过反复试验，而不是计划。

好的问题是相关和有趣的，不太容易回答，但可以用可用或至少在我们能力范围内的材料解决。因此，要想找到好问题，光想是不够的。在我们对一个想法有足够的了解做出正确的判断之前，我们必须对它做一些事情。我们必须在问题上工作、写作、联系、区分、补充和详细阐述——但这就是我们做聪明笔记时所做的。

## 自上而下自下而上

利用我们现有的资源开发主题和问题具有巨大的优势。我们决定的想法不是凭空而来的，而是已经嵌入到内容丰富的环境中，并附带了我们可以使用的材料。从我们所拥有的开始，我们还有另一个意想不到的优势：我们对新想法更加开放。

似乎违反直觉的是，我们对新思想越开放，我们对已经遇到的思想就越熟悉，但科学史学家将乐于证实这一点（Rheinberger 1997）。当你思考它时，它是有意义的：如果没有对我们已经知道的东西进行深入的阐述，我们将很难看到它的局限性，遗漏了什么或可能错了什么。对事物的熟悉使我们能够玩弄它，修改它，发现新的和不同的想法，而不必冒重复旧想法的风险——相信它们是新的。这就是为什么一开始人们会觉得熟悉会让他们更难想出新的想法。我们只是不知道我们的大多数想法实际上并没有那么创新。但是，尽管我们对自己的创造力的信心随着专业知识的增长而下降，但我们实际上更能够做出真正的新贡献。

雅各布·沃伦·盖泽尔斯（Jacob Warren Getzels）和米哈利·齐克森特米哈利（Mihaly Csikszentmihalyi）证明了这一点在艺术中也是正确的：新的、开创性的作品很少是由一个偶然的艺术家创作的，他相信自己具有惊人的创新能力。相反：艺术家花越多的时间去了解一个美学“问题”，他的解决方案就越出人意料，也越有创意，后来就会被艺术专家所重视（Getzels和Csikszentmihalyi 1976）。

如果只需要开放的思想，那么最好的艺术家和科学家就是业余爱好者。杰里米·迪恩（Jeremy Dean）写了大量关于日常生活和仪式的文章，并建议将旧的思维方式视为思维常规。他说得很好，他写道，如果我们甚至没有意识到某种思维方式是一种“确定的”思维方式，我们就无法打破这种思维方式（迪恩，2013）。

## 按照自己的兴趣做事

毫不奇怪，动机被证明是成功学生最重要的指标之一——仅次于掌控自己学习课程的感觉。即使是高智商的学生也会在学习中失败，这通常是因为他们看不到他们应该学习的东西的意义（参见Balduf 2009），无法与他们的个人目标建立联系（Glynn等人，2009），或者缺乏自主控制自己学习的能力（Reeve和Jan，2006；Reeve，2009）。

这些发现是学术自由的重要论据。没有什么比看到一个我们可以认同的项目向前推进更能激励我们的了，没有什么比被困在一个似乎不值得做的项目上更让我们失去动力了。

如果我们事先决定了一个长期项目，却不知道会发生什么，那么对我们所做的事情失去兴趣的风险就很高。通过采用灵活的组织方案，我们可以在必要时改变路线，从而大大降低这一风险。

如果我们在工作的每一步都伴随着这样一个问题：“这件事有什么意思？”我们读到的每一件事都伴随着这样一个问题：“这件事有什么相关性，值得记下来？”我们不仅仅是根据我们的兴趣来选择信息。通过详细阐述我们所遇到的情况，我们也发现了我们以前一无所知的方面，并因此发展了我们的兴趣。如果我们在研究过程中没有改变兴趣，那将是非常悲哀的。

机会主义地改变我们工作方向的能力是一种控制形式，与通过坚持计划来控制环境的尝试完全不同。导致发现DNA结构的研究项目的开始是申请拨款。这笔赠款不是为了发现DNA的结构，而是为了找到一种治疗癌症的方法。如果科学家们信守承诺，他们不仅可能没有找到治疗癌症的方法，而且肯定也不会发现DNA的结构。最有可能的是，他们会对自己的工作失去兴趣。幸运的是，他们没有坚持自己的计划，而是遵循自己的直觉和兴趣，在任何时候都会选择最有希望的洞察之路。实际的研究项目在这一过程中发展（Rheinberger，1997）。可以说，他们在完成整个项目的那一刻就完成了该做什么的计划。

“写一篇文章”这一大任务被分解为小而具体的任务，这使得我们能够控制我们的工作，并在必要时改变方向，这使我们能够实际地在某个时间做需要做的事情，并从中迈出下一步。这不仅仅是感觉在控制中，而是以一种我们真正在控制中的方式来安排工作。我们越是控制自己的工作，就越感兴趣和相关，意志力越弱。只有这样，工作本身才能成为动力的源泉，这对工作的可持续发展至关重要。

```
“当人们对选择有了自主意识时，他们对后续任务的精力并没有减少。值得实证关注的一个重要问题涉及自主选择的潜力，以激活或增强后续任务的自我调节能力。例如，什么样的条件会导致自主选择，从而增强人们对新任务的动机？我们认为，在可能影响选择是否具有活力的因素中，为个人提供的选择的性质。如果一个人在他或她不重视的、琐碎的或不相关的选项中获得了选择，那么即使对某个选项没有微妙的压力，这个选择也不太可能是有活力的，也可能是耗尽的。另一方面，在具有个人价值的选项中进行自主选择可能确实非常令人振奋。” (Moller, 2006,1034)
```

组织工作，使我们能够将我们的项目导向最有希望的方向，这不仅使我们能够更长久地集中精力，而且还能获得更多的乐趣——这是事实（Gilbert 2006）。\[39\]

## 整理和审查

关于最后两个步骤没有什么可说的了，因为主要工作已经完成了。

_一个关键点是：构建文本并保持其灵活性。虽然滑动框非常注重试验和产生新想法，但我们现在需要将我们的想法纳入线性顺序。关键是要明确草案的结构。与其说是一劳永逸地决定在哪一章或哪一段写什么，不如说是在手稿的某一特定部分不需要写什么。通过查看（始终是初步的）结构，您可以看到信息是否会在另一部分中提及。

这一阶段的问题几乎与“空白屏幕”完全相反。我们不知道如何填充页面，而是手头有太多东西，以至于我们不得不抑制同时提及所有内容的冲动。

Zettelkasten的桌面功能是对特定项目的笔记进行排序的地方。它有助于开发一个粗略的结构，但也允许您保持它的灵活性。论点的结构是它的一部分，因此在发展过程中会发生变化——它不是一个装满内容的容器。一旦结构不再有太大变化，我们可以高兴地称之为“目录”。但即使如此，将其视为结构指南而不是处方也是有帮助的。在结尾处改变章节的顺序并不罕见。

_另一个关键点是：尝试同时处理不同的手稿。虽然滑动框已经有助于完成一个项目，但当我们同时开始处理多个项目时，它的真正优势就会发挥出来。滑箱在某种程度上就是化学工业所称的“verbund”。这是一种装置，其中一条生产线不可避免的副产品成为另一条生产线的资源，而另一条生产线又产生了可用于其他工艺的副产品，等等，直到生产线网络高效地交织在一起，不再有孤立的工厂与之竞争。\[40\]

阅读和写作的过程不可避免地会产生许多意想不到的副产品。不是所有的想法都可以放在同一篇文章中，我们遇到的信息中只有一小部分对某个特定项目有用。

如果我们读到了一些有趣但与当前项目不直接相关的东西，我们仍然可以将其用于我们正在或可能正在进行的另一个项目。丰富我们的滑框的一切都有可能最终成为我们可能写的文本。通过智能笔记，我们在一个地方顺便收集材料，以便将来写作。我们从事的项目可能处于完全不同的完成阶段。其中一些甚至可能没有引起我们的注意。这是有利的，不仅因为我们在下一篇论文或书籍上取得了进展，而我们仍在当前的论文或书籍上工作，而且还因为它允许我们在陷入困境或无聊时切换到其他项目。

记住：卢曼对一个人如何能如此高效的问题的回答是，他从不强迫自己做任何事情，只做他容易做的事情。“当我陷入困境时，我会离开它去做其他事情。”当被问到他陷入困境时还做了什么时，他的回答是：“嗯，写其他的书。我总是同时写不同的手稿。用这种方法，同时做不同的事，我从来没有遇到任何精神障碍。”（Luhmann、Baecker和Stanitzek 1987，125–55）这就像武术：如果你遇到阻力或反对力量，你不应该推倒它，而是将它导向另一个富有成效的目标。滑箱总是为你提供多种可能性。

## 放弃规划成为专家

最后一个令人不安的事实是：学生们的计划技能是可怜的。

心理学家罗杰·布勒、戴尔·格里芬和迈克尔·罗斯要求一组学生：

1.实事求是地估计他们完成一篇论文所需的时间。
2.另外估计他们认为需要多长时间

```
a. 如果一切尽可能顺利，或者
b. 如果所有可能出错的事情都会出错。
```

有趣的是，大多数学生的“现实”估计与他们在完美条件下写作的估计并没有太大区别。单凭这一点就应该让他们停下来思考。但是当研究人员检查学生真正需要的时间时，比他们估计的要长得多。甚至没有一半的学生能够在他们认为最糟糕的情况下完成他们的论文（Buehler、Griffin和Ross，1994）。研究人员并没有假设一半的学生突然面临超出他们想象的灾难。

在一年后的另一项研究中，心理学家们更仔细地观察了这一现象，这一现象仍然困扰着他们，因为学生们可以用他们喜欢的任何方式回答问题——给出过于乐观的答案没有任何好处。他们要求学生给他们50%、70%或99%的时间范围来完成论文。

再说一次：他们可以自由地给你任何答案。但是，可以肯定的是，只有45%的人能够在他们认为可能的任何条件下都有99%的可能性完成论文（Buehler、Griffin和Ross 1995）。现在，你可能会认为提醒他们上次的猜测并不完美会有所不同。研究人员这样认为，但学生们证明他们错了：经验似乎并没有教给学生任何东西。

但有一个安慰：这与学生无关。它与人有关。即使是研究这种现象的人，也承认他们也会爱上这种现象，这种现象被称为过度自信偏见（Kahneman 2013，245ff）。

我们要吸取的教训是，对规划普遍持怀疑态度，特别是如果规划仅仅关注结果，而不是实际工作和实现目标所需的步骤。尽管想象自己是一篇成功且及时完成的论文的伟大作者并没有帮助，但如果我们有一个现实的想法，知道需要做些什么才能在我们的脑海中实现这一目标，这确实会有所不同。我们从体育运动中了解到，当运动员把自己想象成一场比赛的胜利者时，这并没有什么帮助，但如果他们把获胜所需的所有训练都想象出来，那会有很大的不同。头脑中有一个更现实的想法不仅有助于他们表现得更好，还可以提高他们的动机（Singer等人，2001年）。我们今天知道，这不仅适用于运动员，也适用于任何需要努力和耐力的工作（Pham和Taylor，1999）。写作肯定属于这一类。

另一个教训不是我们不能从我们的经验中学习，而是我们只能从我们的经验中学习，如果反馈随后很快就会出现——也许会在一段时间内不止一次。将“写一篇论文”这一巨大挑战分解成小的、可管理的任务，有助于设定可定期检查的现实目标。如果有人从一个不切实际的假设出发，认为一篇论文可以按照一个线性计划来写，首先找到一个主题，然后进行文学研究，然后是阅读、思考、写作和校对的分离阶段，因此，基于这一假设的任何时间规划都是不切实际的，这也就不足为奇了。一旦我们做了一些研究，我们可能会发现我们最初的想法没有我们想象的那么好；一旦我们读了一些东西，我们很可能会发现其他的东西可以读，因为这就是我们发现文学的方式；一旦我们开始写下我们的论点，我们很可能会意识到我们需要考虑其他事情，改变我们最初的想法，或者回到一篇我们可能理解得不够透彻的文章。所有这些都不是不寻常的，但所有这些都会打乱任何宏伟的计划。

如果我们开始在某一天写，比如说，三个笔记，回顾前一天写的一段，或者检查我们在一篇文章中发现的所有文献，那么我们在一天结束时就确切地知道我们能够完成什么，并且可以调整我们对第二天的期望。在一年的时间里，我们会收到成百上千的反馈，这将使我们更有可能从中吸取教训，比偶尔错过最后期限更现实地看待我们的生产率，当然，这种情况不会再次发生——直到下一次。

线性模型的问题不仅仅是一个阶段可能需要比计划更长的时间，而且我们不太可能比计划提前完成一个阶段。如果整个问题只是一个判断错误，我们通常会高估我们需要的时间，就像我们低估它一样，但不幸的是，它不是这样工作的。根据著名的帕金森定律，每一种工作都会填满我们为之留出的时间，就像空气充满房间的每个角落一样（帕金森1957）。

虽然这几乎是较长时间范围内的普遍规律，但对于可以一次性完成的任务，情况正好相反。这在一定程度上是由于前面提到的Zeigarnik效应（Zeigarnik 1927），在这种效应中，我们的大脑倾向于一直忙于一项任务，直到它完成（或写下来）。如果我们能看到终点线，我们就会加速，每个人都知道谁跑过马拉松。这意味着最重要的一步是开始。仪式也有帮助（Currey 2013）。

但最大的区别在于你一开始面临的任务。如果下一步像“写一张便条”、“收集本文中有趣的内容”或“将这一系列的便条变成一段”那样可行，那么我们就更容易开始，而不是决定在接下来的几天里花在一项模糊和定义不清的任务上，比如“继续写那篇过期的论文”

## 实际写作

有一次有人问欧内斯特·海明威，他多久重写一次初稿。 

他的回答是：“这要看情况。我把《永别了，武器》的最后一页的结尾重写了39遍，才满意。”

面试官问：“有什么技术问题吗？是什么让你感到困惑？”。

海明威回答说：“把话说对了。”。

如果有一条建议值得提出，那就是记住初稿只是初稿。SlavojŽižek在一次采访中说，\[41\]如果他不先说服自己他只是在为自己写一些想法，他就不可能写出一句话，也许他可以把它变成以后可以发表的东西。当他停止写作时，他总是惊讶地发现，唯一剩下要做的就是修改他已有的草稿。

最困难的任务之一是严格删除论点中没有作用的内容——“杀死你的宝贝。”\[42\]当你将有问题的段落移到另一个文档中并告诉自己以后可能会使用它们时，这会变得容易得多。对于我编写的每个文档，我都有另一个名为“xy rest.doc”的文档，每次我剪切某个内容时，我都会将其复制到另一个文档中，让自己相信我以后会仔细查看它并将其添加回可能适合的位置。当然，这从未发生过——但它仍然有效。其他对心理学略知一二的人也会这样做（参见Thaler，2015，81f）。
