# 养成习惯 {#wind-14}

```
“我们应该养成思考自己所做事情的习惯，这是一个极为错误的真理，所有文案和知名人士在演讲时都会重复这一点。情况恰恰相反。文明的进步是通过扩大我们可以不加思考地执行的重要操作的数量。” (Whitehead)[43]
```

对我们近期行为最可靠的预测是——惊讶，惊讶——做这件事的意图。如果我们现在决定去健身房，那么我们现在就真的去健身房了。但不幸的是，只有在不久的将来才是如此。从长远来看，研究人员很难在我们的意图和实际行为之间找到任何可测量的联系（Ji和Wood，2007年；Neal等人，2012年）。但有一个例外：如果我们碰巧打算做我们以前做过的事情，我们肯定会按照我们的意图行事。

从长远来看，预测人们的行为确实很容易。很有可能，在一个月、一年或两年后，我们会像以前那样做：像以前一样多吃巧克力，像以前一样经常去健身房，像以前一样与伴侣发生同样的争吵。换言之，善意通常不会持续很长时间。

如果我们从行为改变的困难的现实想法开始，我们就有最好的机会在长期内改变我们的行为（Dean 2013）。这并不是那么容易，因为我们越是习惯于用一种特定的方式做某事，我们对它的感觉就越有控制力，即使我们对它的控制力越小。（这在一定程度上也是由于上述单纯的曝光误差。）

```
“那些习惯最强的人在预测未来一周的行为方面最不成功，他们对自己的预测最有信心。这一发现令人震惊，因为它暗示了习惯的阴暗面之一。当我们反复执行某个动作时，它的熟悉程度似乎会重新渗透到我们对该行为的判断中。我们最终感觉自己对行为有了更多的控制，而事实上，我们对这些行为的控制最少。这是我们的思维过程与直觉预期相反的另一个例子。” (Dean 2013, 22)
```

诀窍不是试图打破旧习惯，也不是用意志力强迫自己做其他事情，而是战略性地建立新习惯，有机会取代旧习惯。这里的目标是养成一种习惯，每当我们读到东西的时候就拿笔和纸，写下最重要和最有趣的方面。如果我们能在这第一步中建立一个常规，那么就更容易产生将这些发现转化为永久性记录并将其与滑箱中的其他记录联系起来的冲动。习惯在笔记的外部记忆中思考并不困难，因为它的优点很快就会变得显而易见。一旦我们制定了新的常规，我们就可以做直觉上感觉正确的事情，这不需要任何努力。看着别人读书，除了在一些句子下面划线或做一些没有系统的笔记而什么都不做，这将很快成为一种痛苦的景象。
