\cleardoublepage 

# (APPENDIX) 附录 {-}

# 后记 {#sound}

记智能笔记原则有效。许多成功的作家、艺术家和学者使用某种形式的滑箱。这本书也是借助滑箱写的。例如，有一份关于“技术、验收问题”的说明向我指出，在一本关于集装箱运输历史的书中，可以找到关于为什么有些人难以实施滑箱的问题的答案。我当然不会刻意去寻找——为一本关于有效写作的书做研究！这只是滑箱向我指出的许多想法和联系中的一个。它不仅是一种提高写作效率的工具，也是一种用于长期认真学习的训练手段，这一点我应该很清楚，但事实并非如此。只有当我在最近的学习实验中做了明智的笔记时，我才恍然大悟，我正处于实践中被证明是最有效的。不过，我想指出的是，有时候我自己也有一些想法。

这本书中介绍的特殊技术使尼古拉斯·卢曼成为上个世纪最富有成效和最具创新精神的社会理论家之一。越来越多的学者和非小说作家注意到了这一点。\[44\]但对于大多数学生和作家来说，这仍然不是一件容易的事。这有不同的原因。首先，长期的、跨主题的笔记组织方式，仅以个人的理解和兴趣为指导，与大学和学院课程的模块化、条块化和自上而下的组织方式大相径庭。尽管我们对记忆和学习如何运作的理解发生了根本性的变化，但教学仍处于审查阶段，学生并没有真正被鼓励独立构建异质信息之间的联系网络。有很多关于创新方法的讨论。但是，如果不改变实际的工作流程，这种讨论是没有意义的。一些看似创新的想法，如“以学习者为中心”的方法，往往弊大于利，因为它们仍然忽视了外部支架的需要。学习者不应该成为注意力的焦点。

滑动框不会将学员置于中间位置。恰恰相反：它允许学习者让他或她自己的思想分散在其他思想的网络中。学习、思考和写作不应该是积累知识，而应该是以不同的思维方式成为不同的人。这是通过根据新的经验和事实质疑自己的思维方式来实现的。

线性和以学习者为中心的方法的盛行也导致了人们对使用滑箱作为工具的普遍误解，这种工具可以在不改变其周围工作程序的情况下使用。然后，它通常被简单地用作一个归档文件，在这里，您只需取出先前放入的内容。这当然会导致失望。如果我们只是存储信息，就不需要使用滑箱。为了获得它的好处，我们需要改变我们的工作程序。这一点的基础是深入理解它的工作方式和原因，以及不同的写作步骤和任务是如何结合在一起的。这就是为什么需要一本书而不仅仅是一本手册来解释其背后的原理和思想。

这项技术仍然难以推广的另一个原因是，大多数学生只有在他们已经在努力写作时才意识到需要一个好的系统，通常是在大学课程即将结束时，需要写学士、硕士或博士论文时。这当然仍然有帮助，但如果早一点开始的话，会有更大的帮助——就像为退休储蓄一样。在压力时期也很难改变行为。我们感受到的压力越大，我们就越倾向于坚持我们的老习惯——即使这些习惯首先导致了问题和压力。这被称为隧道效应（Mullainathan和Shafir，2013）。但对这一现象进行彻底研究的穆莱纳坦和沙菲尔也找到了一条出路：当解决方案看似简单时，改变是可能的。

这是最后的好消息。滑箱就这么简单。用手中的笔阅读，记下聪明的笔记，并在它们之间建立联系。想法会自行产生，你的写作也会随之发展。没有必要从头开始。继续做你想做的事：读、想、写。一路上记下漂亮的笔记。

如果您想通过一对一的指导课程开始新的记笔记工作，或者希望得到一些帮助来澄清您对正在写的文章的想法，请查看我在[http://takesmartnotes.com](http://takesmartnotes.com/)
